/* Bioinformatics 互動式考題 — 題庫資料（中英雙語版）
 * Bilingual question bank for the Bioinformatics Interactive Tutorial.
 * 題型 type: "single" 單選 | "multi" 多選 | "tf" 是非
 * 單選 ans: "A"|"B"|"C"|"D"
 * 多選 ans: ["A","C"]
 * 是非 ans: "T"|"F"
 * 中英對照：stem/A/B/C/D/exp 為中文；stem_en/A_en/B_en/C_en/D_en/exp_en 為英文
 */
window.QUIZ_DATA = {
  bioinfo: {
    label: "生物資訊互動考題",
    label_en: "Bioinformatics Interactive Quiz",
    labels_en: {
      "Track 1：Bulk RNA-seq": "Track 1: Bulk RNA-seq",
      "Track 2：Spatial Transcriptomics": "Track 2: Spatial Transcriptomics",
      "Track 3：ATAC-seq / Epigenomics": "Track 3: ATAC-seq / Epigenomics",
      "Track 4：Variant Calling (WGS/WES)": "Track 4: Variant Calling (WGS/WES)",
      "Track 5：Microbiome": "Track 5: Microbiome",
      "Bulk 1：QC 與 Trimming": "Bulk 1: QC & Trimming",
      "Bulk 2：Alignment": "Bulk 2: Alignment",
      "Bulk 3：Quantification": "Bulk 3: Quantification",
      "Bulk 4：Normalization": "Bulk 4: Normalization",
      "Bulk 5：Differential Expression": "Bulk 5: Differential Expression",
      "Bulk 6：Visualization": "Bulk 6: Visualization",
      "Bulk 7：GSEA / Enrichment": "Bulk 7: GSEA / Enrichment",
      "Spatial 1：平台與技術": "Spatial 1: Platforms & Technologies",
      "Spatial 2：Preprocessing": "Spatial 2: Preprocessing",
      "Spatial 3：空間聚類與 SVG": "Spatial 3: Spatial Clustering & SVGs",
      "Spatial 4：Deconvolution": "Spatial 4: Deconvolution",
      "Spatial 5：細胞通訊": "Spatial 5: Cell-Cell Communication",
      "ATAC 1：原理與片段分佈": "ATAC 1: Principles & Fragment Distribution",
      "ATAC 2：Alignment 與 Peak Calling": "ATAC 2: Alignment & Peak Calling",
      "ATAC 3：Motif 與 Footprinting": "ATAC 3: Motif & Footprinting",
      "ATAC 4：多體學整合": "ATAC 4: Multi-omics Integration",
      "Variant 1：Read 預處理": "Variant 1: Read Preprocessing",
      "Variant 2：Variant Calling": "Variant 2: Variant Calling",
      "Variant 3：Filtering": "Variant 3: Filtering",
      "Variant 4：Annotation": "Variant 4: Annotation",
      "Variant 5：SV / CNV": "Variant 5: SV / CNV",
      "Microbiome 1：16S Amplicon": "Microbiome 1: 16S Amplicon",
      "Microbiome 2：Shotgun Metagenomics": "Microbiome 2: Shotgun Metagenomics",
      "Microbiome 3：Functional Profiling": "Microbiome 3: Functional Profiling"
    },
    subjects: {
      "Track 1：Bulk RNA-seq": {
        "Bulk 1：QC 與 Trimming": [
          { type:"single",
            stem:"FASTQ 品質分數 Q 與錯誤率 P 之間的數學關係為何？",
            stem_en:"What is the mathematical relationship between FASTQ quality Q and error rate P?",
            A:"Q = P × 100", A_en:"Q = P × 100",
            B:"Q = 10·ln(P)", B_en:"Q = 10·ln(P)",
            C:"Q = -10·log10(P)", C_en:"Q = -10·log10(P)",
            D:"Q 與 P 無數學關係", D_en:"No mathematical relation",
            ans:"C",
            exp:"Phred 分數 Q = -10·log10(P)。Q20 對應 1%、Q30 對應 0.1%、Q40 對應 0.01% 錯誤率。",
            exp_en:"Phred score Q = -10·log10(P). Q20 → 1%, Q30 → 0.1%, Q40 → 0.01% error rate." },
          { type:"single",
            stem:"FastQC 報告中「Per base sequence content」前 10-12 bp 出現不平衡通常是？",
            stem_en:"Imbalance in FastQC 'Per base sequence content' at the first 10-12 bp is usually due to?",
            A:"嚴重的接頭汙染", A_en:"Severe adapter contamination",
            B:"random hexamer priming 偏差，屬正常", B_en:"Random hexamer priming bias — normal",
            C:"基因組 GC 偏好", C_en:"Genome GC bias",
            D:"樣本退化", D_en:"Sample degradation",
            ans:"B",
            exp:"標準 RNA-seq 用 random hexamer 反轉錄，導致前 10-12 bp 鹼基分布偏向特定組合。這是已知偏差，不需 trim。",
            exp_en:"Standard RNA-seq uses random hexamer priming, biasing the first 10-12 bp. This is a known artifact — no need to trim." },
          { type:"single",
            stem:"下列哪一個 trimming 工具最適合「速度優先 + 一次完成 QC、trim、報告」的需求？",
            stem_en:"Which trimming tool best fits the need 'speed-first + one-shot QC, trim, and report'?",
            A:"Trimmomatic", A_en:"Trimmomatic",
            B:"cutadapt", B_en:"cutadapt",
            C:"fastp", C_en:"fastp",
            D:"trim_galore", D_en:"trim_galore",
            ans:"C",
            exp:"fastp 是多執行緒、一次完成 QC + trim + HTML 報告的工具，速度最快。",
            exp_en:"fastp is multi-threaded and produces QC + trim + HTML report in one pass; the fastest option." },
          { type:"multi",
            stem:"下列哪些是合理的 trimming 預設參數選擇？（多選）",
            stem_en:"Which of the following are reasonable default trimming parameters? (Multiple)",
            A:"min Q = 20", A_en:"min Q = 20",
            B:"min length = 36 bp", B_en:"min length = 36 bp",
            C:"min length = 5 bp", C_en:"min length = 5 bp",
            D:"自動偵測接頭", D_en:"Auto-detect adapter",
            ans:["A","B","D"],
            exp:"Q20 與 length 36 是業界常見起點；自動偵測接頭可避免手動指定錯誤。Length=5 過低會留下無法比對的短 read。",
            exp_en:"Q20 and length 36 are standard starting points; auto-detect avoids manual adapter errors. Length=5 retains unmappable shorts." },
          { type:"tf",
            stem:"是非題：MultiQC 可以彙整多個 FastQC、STAR、Salmon 等工具的 log 為單一 HTML 報告。",
            stem_en:"True/False: MultiQC can aggregate logs from FastQC, STAR, Salmon, and others into one HTML report.",
            ans:"T",
            exp:"這正是 MultiQC 的核心功能，被廣泛用於 RNA-seq 管線的最終 QC 整合。",
            exp_en:"This is MultiQC's core purpose, widely used as the final QC integration step in RNA-seq pipelines." },
          { type:"tf",
            stem:"是非題：FASTQ 品質分數採用 Phred+33 編碼後，ASCII 字元 'A' (十進位 65) 對應 Q32。",
            stem_en:"True/False: In Phred+33 encoding, ASCII character 'A' (decimal 65) corresponds to Q32.",
            ans:"T",
            exp:"Phred+33：Q = ASCII - 33。'A' 的 ASCII 為 65，所以 Q = 65 - 33 = 32。",
            exp_en:"Phred+33: Q = ASCII - 33. ASCII for 'A' is 65, so Q = 65 - 33 = 32." },
          { type:"single",
            stem:"修剪後 reads 過短（如 &lt; 25 bp）通常代表？",
            stem_en:"Very short reads after trimming (e.g., &lt; 25 bp) usually indicate?",
            A:"原始 reads 品質極佳", A_en:"Excellent raw read quality",
            B:"insert 過短，read 讀穿到接頭", B_en:"Insert too short — read sequenced through adapter",
            C:"PCR duplicate 嚴重", C_en:"Severe PCR duplication",
            D:"接頭序列偵測失敗", D_en:"Adapter detection failed",
            ans:"B",
            exp:"insert 過短時，read 會讀過 cDNA 末端進入接頭序列，trim 完只剩很短的有效部分。",
            exp_en:"If the insert is too short, reads run past the cDNA end into adapter; after trimming only a short useful portion remains." },
          { type:"single",
            stem:"關於 FASTQ 中的 Phred 分數，下列何者錯誤？",
            stem_en:"Which statement about Phred quality in FASTQ is INCORRECT?",
            A:"Q30 代表錯誤率 0.1%", A_en:"Q30 indicates 0.1% error rate",
            B:"現代 Illumina 平台多數鹼基為 Q30+", B_en:"Modern Illumina platforms produce mostly Q30+",
            C:"3' 端品質下滑屬正常現象", C_en:"Quality drop at 3' end is normal",
            D:"Q40 代表 100% 準確", D_en:"Q40 means 100% accuracy",
            ans:"D",
            exp:"Q40 代表錯誤率 0.01%（萬分之一），並非 100% 準確。",
            exp_en:"Q40 means 0.01% error rate (1 in 10,000), not 100% accuracy." }
        ],
        "Bulk 2：Alignment": [
          { type:"single",
            stem:"下列何者輸出 BAM 檔，可用於 IGV 視覺化與變異偵測？",
            stem_en:"Which tool produces BAM suitable for IGV visualization and variant calling?",
            A:"Salmon", A_en:"Salmon",
            B:"kallisto", B_en:"kallisto",
            C:"STAR", C_en:"STAR",
            D:"FastQC", D_en:"FastQC",
            ans:"C",
            exp:"STAR 與 HISAT2 是基因組比對器，輸出含座標的 BAM。Salmon / kallisto 為 pseudo-aligner，不輸出位置資訊。",
            exp_en:"STAR and HISAT2 are genome aligners producing coordinate-aware BAM. Salmon / kallisto are pseudo-aligners without coordinates." },
          { type:"single",
            stem:"Salmon 中的 <code>--gcBias</code> 旗標主要校正什麼？",
            stem_en:"What does Salmon's <code>--gcBias</code> flag correct?",
            A:"片段 GC 含量造成的覆蓋偏差", A_en:"Fragment-GC-content coverage bias",
            B:"接頭汙染", B_en:"Adapter contamination",
            C:"批次效應", C_en:"Batch effect",
            D:"PCR 重複", D_en:"PCR duplicates",
            ans:"A",
            exp:"GC bias 源自 PCR 與片段化偏好，<code>--gcBias</code> 進行片段層級的偏差校正。",
            exp_en:"GC bias arises from PCR / fragmentation; <code>--gcBias</code> performs fragment-level correction." },
          { type:"single",
            stem:"以下何者是 STAR 比對的主要記憶體消耗來源？",
            stem_en:"What is the primary memory consumer when running STAR?",
            A:"BAM 輸出緩衝區", A_en:"BAM output buffer",
            B:"基因組 Suffix Array 索引", B_en:"Genome suffix array index",
            C:"FASTQ 解壓", C_en:"FASTQ decompression",
            D:"GTF 註釋檔", D_en:"GTF annotation",
            ans:"B",
            exp:"STAR 將基因組與註釋的 SA 索引整個載入記憶體；人類 GRCh38 大約需要 30 GB RAM。",
            exp_en:"STAR loads the genome + annotation suffix-array index into RAM; human GRCh38 needs ~30 GB." },
          { type:"multi",
            stem:"下列哪些工具屬於「pseudo-alignment / selective alignment」家族？（多選）",
            stem_en:"Which tools belong to the pseudo / selective alignment family? (Multiple)",
            A:"Salmon", A_en:"Salmon",
            B:"kallisto", B_en:"kallisto",
            C:"STAR", C_en:"STAR",
            D:"HISAT2", D_en:"HISAT2",
            ans:["A","B"],
            exp:"Salmon (selective alignment) 與 kallisto (pseudo-alignment) 屬同類；STAR 與 HISAT2 為傳統 splice-aware aligner。",
            exp_en:"Salmon (selective alignment) and kallisto (pseudo-alignment) are in the same family; STAR / HISAT2 are splice-aware aligners." },
          { type:"tf",
            stem:"是非題：ENCODE 對 RNA-seq 樣本的建議深度為 30 M paired-end reads。",
            stem_en:"True/False: ENCODE recommends 30 M paired-end reads for RNA-seq samples.",
            ans:"T",
            exp:"ENCODE 建議 30 M PE 作為一般 differential expression 分析的目標深度。深度需求隨 splicing / 低豐度基因偵測需求提升。",
            exp_en:"ENCODE recommends 30 M PE as a standard target for DE analysis. Depth needs scale with splicing / rare-transcript detection." },
          { type:"single",
            stem:"RNA-seq 比對結果中「mapped to too many loci」比例 &gt; 5% 最可能的原因是？",
            stem_en:"In RNA-seq alignment, '% mapped to too many loci' &gt; 5% most likely indicates?",
            A:"接頭未 trim 乾淨", A_en:"Adapters not fully trimmed",
            B:"rRNA / 重複序列汙染", B_en:"rRNA / repetitive sequence contamination",
            C:"資料量太少", C_en:"Too little data",
            D:"GC bias 偏高", D_en:"High GC bias",
            ans:"B",
            exp:"rRNA 或重複序列在基因組多處出現，一條 read 同時對應多個位置，會被歸入 multimapper。",
            exp_en:"rRNA or repetitive sequences appear in multiple loci; reads mapping to all of them are flagged as multimappers." },
          { type:"single",
            stem:"關於 BAM 與 SAM 檔案，下列敘述何者正確？",
            stem_en:"Which statement about BAM and SAM is correct?",
            A:"SAM 是壓縮後二進位格式", A_en:"SAM is the compressed binary format",
            B:"BAM 是 SAM 的二進位壓縮版", B_en:"BAM is the binary compressed form of SAM",
            C:"兩者只能擇一輸出", C_en:"They are mutually exclusive",
            D:"BAM 不支援索引", D_en:"BAM does not support indexing",
            ans:"B",
            exp:"BAM 是 SAM 的 BGZF 壓縮版二進位格式，可被 samtools index 建立 .bai 索引，IGV 可隨機讀取。",
            exp_en:"BAM is the BGZF-compressed binary form of SAM, indexable by samtools index (.bai), enabling random access in IGV." }
        ],
        "Bulk 3：Quantification": [
          { type:"single",
            stem:"下列哪個量化單位最適合餵給 DESeq2 進行差異表達分析？",
            stem_en:"Which quantification unit is best fed into DESeq2 for DE analysis?",
            A:"log2(TPM + 1)", A_en:"log2(TPM + 1)",
            B:"FPKM", B_en:"FPKM",
            C:"raw integer counts", C_en:"Raw integer counts",
            D:"CPM", D_en:"CPM",
            ans:"C",
            exp:"DE 工具基於負二項分佈建模，需要原始整數 counts。TPM/FPKM 已失去 library size 資訊與 mean-variance 結構。",
            exp_en:"DE tools assume negative-binomial integer counts. TPM/FPKM lose library size and mean-variance structure." },
          { type:"single",
            stem:"featureCounts 對 dUTP（反鏈）library 應該設 <code>-s</code> 為？",
            stem_en:"For a dUTP (reverse-stranded) library, <code>-s</code> in featureCounts should be?",
            A:"0 (unstranded)", A_en:"0 (unstranded)",
            B:"1 (forward stranded)", B_en:"1 (forward stranded)",
            C:"自動偵測", C_en:"Auto detect",
            D:"2 (reverse stranded)", D_en:"2 (reverse stranded)",
            ans:"D",
            exp:"dUTP library 為反鏈，需 <code>-s 2</code>。設錯會少算 50% 以上 counts。",
            exp_en:"dUTP libraries are reverse-stranded; use <code>-s 2</code>. Wrong setting drops &gt; 50% counts." },
          { type:"single",
            stem:"tximport 在 RNA-seq 流程中扮演什麼角色？",
            stem_en:"What role does tximport play in the RNA-seq workflow?",
            A:"進行差異表達分析", A_en:"Performs DE analysis",
            B:"把 Salmon/kallisto 轉錄本層級估計值整合成基因層級 counts", B_en:"Aggregates Salmon/kallisto transcript estimates into gene-level counts",
            C:"做基因註釋", C_en:"Annotates genes",
            D:"產生 PCA 圖", D_en:"Generates PCA plots",
            ans:"B",
            exp:"tximport 把 Salmon/kallisto 的 transcript 估計值（含 length-scaling 校正）整合成 gene-level matrix，可直接餵 DESeq2。",
            exp_en:"tximport aggregates transcript-level Salmon/kallisto estimates (with length scaling) into a gene-level matrix for DESeq2." },
          { type:"multi",
            stem:"下列哪些是 featureCounts 對 paired-end RNA-seq 必須注意的設定？（多選）",
            stem_en:"For paired-end RNA-seq, which featureCounts settings are critical? (Multiple)",
            A:"加 <code>-p --countReadPairs</code>", A_en:"Add <code>-p --countReadPairs</code>",
            B:"正確的 <code>-s</code> strandedness", B_en:"Correct <code>-s</code> strandedness",
            C:"<code>-t exon -g gene_id</code> 標準聚合層級", C_en:"<code>-t exon -g gene_id</code> for standard aggregation",
            D:"必須 <code>--primary</code> 才能跑", D_en:"<code>--primary</code> is mandatory to run",
            ans:["A","B","C"],
            exp:"A 防止雙倍灌水、B 防止漏算、C 是標準 gene-level 設定。<code>--primary</code> 是可選參數。",
            exp_en:"A prevents double-counting; B prevents undercounting; C is the standard gene-level setting. <code>--primary</code> is optional." },
          { type:"tf",
            stem:"是非題：TPM 在跨樣本比較單一基因時通常比 FPKM 更穩定。",
            stem_en:"True/False: TPM is typically more stable than FPKM when comparing a single gene across samples.",
            ans:"T",
            exp:"Wagner et al. 2012 證明 TPM 的「先 normalize by length 再 normalize by sum」順序確保總和恆為 10⁶，使樣本間單一基因比較更一致。",
            exp_en:"Wagner et al. 2012 showed TPM's 'normalize-by-length then normalize-by-sum' guarantees sum to 10⁶, making single-gene cross-sample comparisons more consistent." },
          { type:"single",
            stem:"以下對表達量「raw count」的描述何者正確？",
            stem_en:"Which is correct about 'raw counts' of expression?",
            A:"是分配到基因的 read 整數", A_en:"Integer reads assigned to a gene",
            B:"已標準化為跨樣本比較單位", B_en:"Already normalized for cross-sample comparison",
            C:"以小數呈現", C_en:"Reported as decimals",
            D:"已經 log 轉換", D_en:"Already log-transformed",
            ans:"A",
            exp:"raw count 是分配到基因的 read 整數；DESeq2 / edgeR 都從 raw count 起算 size factor 與 dispersion。",
            exp_en:"Raw counts are integer reads assigned to a gene; DESeq2 / edgeR compute size factor and dispersion from raw counts." },
          { type:"tf",
            stem:"是非題：用 TPM 直接做 t-test 找 DEG 是統計上合理的做法。",
            stem_en:"True/False: Running a t-test on TPMs to find DEGs is statistically valid.",
            ans:"F",
            exp:"TPM 已失去 library size 與 mean-variance 結構，且不符合 t-test 的常態假設；應用 DESeq2/edgeR/voom 等專屬模型。",
            exp_en:"TPM loses library size and mean-variance structure; it also violates t-test normality. Use DESeq2/edgeR/voom instead." }
        ],
        "Bulk 4：Normalization": [
          { type:"single",
            stem:"什麼是 composition bias 的核心特徵？",
            stem_en:"What characterizes composition bias?",
            A:"整體 library size 不同", A_en:"Different total library sizes",
            B:"少數基因表達差異極大，吃掉其他基因的 read share", B_en:"A few genes change dramatically, stealing read share from others",
            C:"基因長度的 GC 含量不同", C_en:"GC content varies with gene length",
            D:"PCR 重複造成的 inflation", D_en:"PCR duplicate inflation",
            ans:"B",
            exp:"當某些基因表達巨變（如組織特異基因暴衝），會壓縮其他基因在 library 中的相對 reads，造成假象的 down-regulation。",
            exp_en:"When a few genes change dramatically, they steal read share — causing apparent down-regulation in unchanged genes." },
          { type:"single",
            stem:"DESeq2 進行 PCA 前，最推薦先做什麼轉換？",
            stem_en:"What's the recommended transform before PCA in DESeq2?",
            A:"log2(raw + 1)", A_en:"log2(raw + 1)",
            B:"log2(TPM + 1)", B_en:"log2(TPM + 1)",
            C:"vst() 或 rlog()", C_en:"vst() or rlog()",
            D:"quantile normalization", D_en:"Quantile normalization",
            ans:"C",
            exp:"vst / rlog 校正 mean-variance 關係，避免低 counts 基因的高變異主導 PCA。是 DESeq2 工作流的官方建議。",
            exp_en:"vst / rlog stabilize the mean-variance relationship; otherwise low-count genes dominate PCA. Official DESeq2 recommendation." },
          { type:"single",
            stem:"edgeR 的 <code>calcNormFactors()</code> 預設使用哪種方法？",
            stem_en:"Which method does edgeR's <code>calcNormFactors()</code> use by default?",
            A:"TMM", A_en:"TMM",
            B:"RLE", B_en:"RLE",
            C:"upperquartile", C_en:"Upperquartile",
            D:"none", D_en:"none",
            ans:"A",
            exp:"edgeR 預設使用 TMM (Trimmed Mean of M-values)，假設多數基因不變異，以 trimmed mean 估計 normalization factor。",
            exp_en:"edgeR defaults to TMM (Trimmed Mean of M-values), assuming most genes don't change and using a trimmed mean to estimate the factor." },
          { type:"tf",
            stem:"是非題：DESeq2 內建 size factor 估算，因此用 raw counts 直接作為輸入即可，不需手動正規化。",
            stem_en:"True/False: DESeq2 estimates size factors internally, so raw counts can be fed directly without manual normalization.",
            ans:"T",
            exp:"DESeq2 的 <code>DESeq()</code> 函式內含 <code>estimateSizeFactors()</code>；使用者只需提供 raw counts。",
            exp_en:"DESeq2's <code>DESeq()</code> calls <code>estimateSizeFactors()</code> internally; just supply raw counts." },
          { type:"multi",
            stem:"下列哪些情境會讓「簡單除以 library size 後的 CPM」失準？（多選）",
            stem_en:"In which scenarios does 'CPM = raw / library size' become misleading? (Multiple)",
            A:"有少數基因暴衝（composition bias）", A_en:"A few genes are dominant (composition bias)",
            B:"樣本間 RNA 質量不同", B_en:"RNA quality differs between samples",
            C:"批次效應", C_en:"Batch effects",
            D:"所有樣本表達極度均勻", D_en:"All samples are perfectly uniform",
            ans:["A","B","C"],
            exp:"前三項都會破壞 CPM 的可比性；只有樣本完美均勻時 CPM 才精準（現實中極罕見）。",
            exp_en:"The first three break CPM's comparability; only perfectly uniform samples make CPM accurate (rare in practice)." },
          { type:"single",
            stem:"在做基因表達熱圖 (heatmap) 時，最常見的 row scaling 操作是？",
            stem_en:"For gene-expression heatmaps, the most common row-scaling operation is?",
            A:"divide by row max", A_en:"Divide by row max",
            B:"z-score (per gene centered & scaled)", B_en:"z-score (per gene centered & scaled)",
            C:"min-max to [0,1]", C_en:"Min-max to [0,1]",
            D:"取對數", D_en:"Log transform",
            ans:"B",
            exp:"z-score 讓每個基因有相同的 scale，避免高表達基因永遠是紅色、低表達永遠是藍色而看不見模式。",
            exp_en:"z-score puts all genes on the same scale, preventing highly expressed genes from being permanently red and lows permanently blue." },
          { type:"single",
            stem:"以下何者較適合用來訓練機器學習模型的特徵？",
            stem_en:"Which is more suitable as features for machine-learning models?",
            A:"raw counts", A_en:"raw counts",
            B:"TPM", B_en:"TPM",
            C:"vst 轉換後 + z-score", C_en:"vst-transformed + z-score",
            D:"百分位數 rank", D_en:"Percentile rank",
            ans:"C",
            exp:"vst 穩定方差使不同表達量的基因等比例貢獻；再做 z-score 進一步移除尺度差異，是 ML 特徵的標準前處理。",
            exp_en:"vst stabilizes variance so genes contribute proportionally; z-score then removes scale differences — standard ML preprocessing." }
        ],
        "Bulk 5：Differential Expression": [
          { type:"single",
            stem:"RNA-seq counts 的「過度離散」(over-dispersion) 是指？",
            stem_en:"'Over-dispersion' in RNA-seq counts means?",
            A:"樣本之間的 library size 差異", A_en:"Library-size differences between samples",
            B:"variance 遠大於 mean，違反 Poisson 假設", B_en:"Variance ≫ mean, violating Poisson assumption",
            C:"高表達基因比低表達基因多", C_en:"More highly than lowly expressed genes",
            D:"偵測到太多 DEG", D_en:"Too many DEGs detected",
            ans:"B",
            exp:"Poisson 假設 var = mean；RNA-seq 實際 variance &gt; mean，故用負二項分佈建模。DESeq2、edgeR 均建立於此。",
            exp_en:"Poisson assumes var = mean; RNA-seq has var &gt; mean, so the negative binomial is used. DESeq2 and edgeR are built on this." },
          { type:"single",
            stem:"何時最該使用 DESeq2 的 <code>lfcShrink()</code>？",
            stem_en:"When is DESeq2's <code>lfcShrink()</code> most useful?",
            A:"取代 p-value 校正", A_en:"Replace p-value adjustment",
            B:"增加 DEG 數量", B_en:"Increase DEG count",
            C:"依 LFC 排名挑 top 基因時，減低低 counts 基因的假象高 LFC", C_en:"When ranking by LFC — tame inflated LFCs from low-count genes",
            D:"改善樣本對齊率", D_en:"Improve sample alignment rate",
            ans:"C",
            exp:"shrinkage 用 Bayesian prior 把低 counts 基因高估的 LFC 拉回，使排名更可靠；特別適合 GSEA 與 top-list 選擇。",
            exp_en:"Shrinkage uses a Bayesian prior to tame inflated LFCs from low counts, yielding reliable ranking for GSEA and top lists." },
          { type:"single",
            stem:"使用 DESeq2 時，<code>~ batch + condition</code> 這種 design 公式的意義是？",
            stem_en:"In DESeq2, what does the design <code>~ batch + condition</code> mean?",
            A:"只比較 batch 之間差異", A_en:"Compares only batches",
            B:"在控制 batch 影響下測試 condition 效應", B_en:"Tests condition effect while adjusting for batch",
            C:"忽略 batch", C_en:"Ignore batch",
            D:"先做 condition 再做 batch", D_en:"Do condition first, then batch",
            ans:"B",
            exp:"設計矩陣加入 batch 作為協變量，模型在控制 batch 的條件下估計 condition 的差異效應。",
            exp_en:"Adding batch as a covariate lets the model estimate condition effects while adjusting for batch." },
          { type:"multi",
            stem:"下列哪些是 RNA-seq DE 分析的主流套件？（多選）",
            stem_en:"Which are mainstream tools for RNA-seq DE analysis? (Multiple)",
            A:"DESeq2", A_en:"DESeq2",
            B:"edgeR", B_en:"edgeR",
            C:"limma-voom", C_en:"limma-voom",
            D:"Wilcoxon rank-sum test 對 raw counts", D_en:"Wilcoxon rank-sum on raw counts",
            ans:["A","B","C"],
            exp:"DESeq2、edgeR、limma-voom 是 bulk RNA-seq DE 的三大主流。直接對 raw counts 做 Wilcoxon 沒有處理離散度與 library size，並非主流選擇。",
            exp_en:"DESeq2, edgeR, and limma-voom are the three mainstream bulk RNA-seq DE tools. Plain Wilcoxon on raw counts ignores dispersion and library size — not mainstream." },
          { type:"tf",
            stem:"是非題：在 RNA-seq DE 分析中，padj &lt; 0.05 通常意味通過 Benjamini-Hochberg (BH) 多重比較校正。",
            stem_en:"True/False: In RNA-seq DE, padj &lt; 0.05 typically means passing Benjamini-Hochberg (BH) multiple-test correction.",
            ans:"T",
            exp:"DESeq2 / edgeR 預設使用 BH (FDR) 校正；padj 即 BH-adjusted p-value。",
            exp_en:"DESeq2 / edgeR default to BH (FDR) correction; padj is the BH-adjusted p-value." },
          { type:"single",
            stem:"關於「baseMean 極低但 LFC 巨大」的 DE 結果，最合理的解讀是？",
            stem_en:"For a DE result with very low baseMean but huge LFC, the most reasonable interpretation is?",
            A:"高信心顯著差異", A_en:"High-confidence significant difference",
            B:"低表達基因易因少數 outlier 造成 LFC 膨脹，須謹慎", B_en:"Low-expression genes easily get LFC inflation from outliers — interpret cautiously",
            C:"必為實驗錯誤", C_en:"Must be experimental error",
            D:"必有臨床意義", D_en:"Must have clinical significance",
            ans:"B",
            exp:"低 baseMean 對少數 reads 的擾動極敏感，LFC 容易被高估；lfcShrink 正是為了處理這種情形。",
            exp_en:"Low baseMean is sensitive to a few reads, inflating LFC; lfcShrink is designed precisely for this case." },
          { type:"single",
            stem:"以下何者最適合處理「樣本配對（paired）」的實驗設計？",
            stem_en:"Which best handles 'paired' experimental designs?",
            A:"design = ~ condition（忽略配對）", A_en:"design = ~ condition (ignore pairing)",
            B:"design = ~ subject + condition", B_en:"design = ~ subject + condition",
            C:"design = ~ 1", C_en:"design = ~ 1",
            D:"完全不用 DESeq2", D_en:"Don't use DESeq2",
            ans:"B",
            exp:"加入 subject 為協變量可移除個體差異，提升統計效力。配對設計常見於 pre/post 治療樣本。",
            exp_en:"Adding subject as a covariate removes inter-individual variation, increasing power. Common in pre/post-treatment paired designs." },
          { type:"single",
            stem:"以下何者最能解釋為什麼小樣本 (n=3 vs 3) 仍可進行 DE 分析？",
            stem_en:"What best explains why DE analysis is feasible with very small samples (n=3 vs 3)?",
            A:"全基因組同時做檢定提供大量平均資訊", A_en:"Testing all genes jointly provides large pooled information",
            B:"DESeq2 / edgeR 透過跨基因資訊估計 dispersion（empirical Bayes shrinkage）", B_en:"DESeq2 / edgeR borrow information across genes for dispersion (empirical Bayes shrinkage)",
            C:"小樣本本質上比大樣本準", C_en:"Small samples are inherently more accurate",
            D:"DE 分析不需估計變異", D_en:"DE analysis doesn't estimate variance",
            ans:"B",
            exp:"empirical Bayes shrinkage 借用其他基因的 dispersion 來改善單一基因的變異估計，是 DESeq2 / edgeR 對小 n 的關鍵能力。",
            exp_en:"Empirical Bayes shrinkage borrows dispersion across genes, stabilizing per-gene variance — the key reason DESeq2 / edgeR work for small n." },
          { type:"tf",
            stem:"是非題：若已用 DESeq2 估計 size factor，那麼跑 DESeq2 前還應該再做 TPM 正規化。",
            stem_en:"True/False: After DESeq2 estimates size factors, you should also TPM-normalize before running DESeq2.",
            ans:"F",
            exp:"DESeq2 的 size factor 已處理 library size 與 composition bias。TPM 化反而會破壞統計模型的 mean-variance 結構。",
            exp_en:"DESeq2's size factor already handles library size and composition bias. TPM-normalizing destroys the model's mean-variance structure." }
        ],
        "Bulk 6：Visualization": [
          { type:"single",
            stem:"Volcano plot 的 X 軸與 Y 軸通常是什麼？",
            stem_en:"What are the X and Y axes of a volcano plot?",
            A:"X: log2FC、Y: padj", A_en:"X: log2FC, Y: padj",
            B:"X: log2FC、Y: -log10(padj)", B_en:"X: log2FC, Y: -log10(padj)",
            C:"X: -log10(padj)、Y: log2FC", C_en:"X: -log10(padj), Y: log2FC",
            D:"X: gene index、Y: expression", D_en:"X: gene index, Y: expression",
            ans:"B",
            exp:"Volcano plot 標準格式：X = log2 fold change，Y = -log10(padj)。右上 = 顯著上調，左上 = 顯著下調。",
            exp_en:"Standard volcano: X = log2 fold change, Y = -log10(padj). Upper-right = significant up; upper-left = significant down." },
          { type:"single",
            stem:"MA-plot 在 RNA-seq 中能回答下列哪個問題？",
            stem_en:"What question does an MA-plot answer in RNA-seq?",
            A:"批次效應", A_en:"Batch effect",
            B:"表達強度與 LFC 的關係，是否有 LFC 偏移", B_en:"Relationship between expression intensity and LFC; any LFC bias",
            C:"細胞類型組成", C_en:"Cell-type composition",
            D:"PCR 重複", D_en:"PCR duplicates",
            ans:"B",
            exp:"MA-plot X = log mean expression、Y = LFC。理想情況下多數點集中在 LFC = 0，DEG 散落上下方。",
            exp_en:"MA-plot X = log mean expression, Y = LFC. Most points should cluster at LFC=0 with DEGs above/below." },
          { type:"single",
            stem:"PCA 圖中「條件主導 PC1」代表什麼？",
            stem_en:"In a PCA plot, 'condition dominates PC1' means?",
            A:"批次效應嚴重", A_en:"Severe batch effect",
            B:"case 與 control 在 PC1 完美分開，生物學訊號強", B_en:"Case and control separate cleanly along PC1 — strong biological signal",
            C:"資料無變異", C_en:"Data has no variance",
            D:"PCA 失敗", D_en:"PCA failed",
            ans:"B",
            exp:"PC1 抓最大變異方向。若沿 PC1 完美分開 case/ctrl，代表條件效應是最強的變異來源。",
            exp_en:"PC1 captures the largest variance. Clean separation along PC1 means condition is the dominant variance source." },
          { type:"tf",
            stem:"是非題：直接以 raw counts 做 PCA，主成分主要反映 library size 差異。",
            stem_en:"True/False: Running PCA directly on raw counts means PCs mainly reflect library-size differences.",
            ans:"T",
            exp:"raw counts variance 被 library size 主導，PCA 結果常呈現「樣本間總量」差異而非生物學差異。應先 vst / rlog。",
            exp_en:"Raw-count variance is dominated by library size; PCA shows depth differences instead of biology. Use vst / rlog first." },
          { type:"single",
            stem:"在 ComplexHeatmap 或 pheatmap 中，<code>scale = \"row\"</code> 的作用是？",
            stem_en:"In ComplexHeatmap / pheatmap, what does <code>scale = \"row\"</code> do?",
            A:"對每個樣本縮放", A_en:"Scale by sample",
            B:"對每個基因做 z-score（centering + scaling）", B_en:"z-score each gene (centering + scaling)",
            C:"對整個矩陣 min-max", C_en:"Min-max the whole matrix",
            D:"log 轉換", D_en:"Log transform",
            ans:"B",
            exp:"row scaling 對每個基因做 z-score，讓各基因在熱圖中以相對表達量呈現，模式更明顯。",
            exp_en:"Row scaling z-scores each gene, displaying relative expression so patterns become visible." }
        ],
        "Bulk 7：GSEA / Enrichment": [
          { type:"single",
            stem:"下列何種情境較適合 GSEA 而非 ORA？",
            stem_en:"Which scenario favors GSEA over ORA?",
            A:"有明確的 100 個 DEG list", A_en:"A clear list of 100 DEGs",
            B:"沒有強訊號但某 pathway 內基因整體略偏向上調", B_en:"No strong hits but a pathway is collectively, mildly up-regulated",
            C:"想知道單一基因表達", C_en:"Single-gene expression query",
            D:"樣本量極小 (n=2)", D_en:"Very small n (n=2)",
            ans:"B",
            exp:"GSEA 無門檻、使用整體排序，能捕捉「集體微幅變化」。ORA 需要明確 DEG list 才能跑。",
            exp_en:"GSEA uses the full ranked list without cutoff, capturing coordinated small changes. ORA needs an explicit DEG list." },
          { type:"single",
            stem:"GSEA 的「leading edge」指的是？",
            stem_en:"What is GSEA's 'leading edge'?",
            A:"在 ES 達峰前出現的基因——實際撐起 enrichment 的子集", A_en:"Genes appearing before the ES peak — the subset actually driving enrichment",
            B:"最大 LFC 的單一基因", B_en:"The single highest LFC gene",
            C:"所有 padj &lt; 0.05 的基因", C_en:"All genes with padj &lt; 0.05",
            D:"p &gt; 0.05 的所有基因", D_en:"Genes with p &gt; 0.05",
            ans:"A",
            exp:"leading edge 是 ES 達峰前的基因——這些是該 pathway 中真正驅動 enrichment 的核心子集。",
            exp_en:"Leading edge = genes before the ES peak — the core subset driving the enrichment of that pathway." },
          { type:"multi",
            stem:"下列哪些是 ORA / GSEA 常用的 gene set 資料庫？（多選）",
            stem_en:"Which are common gene-set databases for ORA / GSEA? (Multiple)",
            A:"GO (BP/MF/CC)", A_en:"GO (BP/MF/CC)",
            B:"KEGG", B_en:"KEGG",
            C:"MSigDB Hallmark", C_en:"MSigDB Hallmark",
            D:"GenBank", D_en:"GenBank",
            ans:["A","B","C"],
            exp:"GO、KEGG、MSigDB Hallmark 都是 enrichment 主流資料庫。GenBank 是序列資料庫，與 enrichment 無關。",
            exp_en:"GO, KEGG, and MSigDB Hallmark are mainstream enrichment DBs. GenBank is a sequence database, not for enrichment." },
          { type:"tf",
            stem:"是非題：ORA 的 background（universe）應該是「實驗中可偵測到的所有基因」，而非整個基因組。",
            stem_en:"True/False: For ORA, the background (universe) should be 'all genes detectable in the experiment', not the whole genome.",
            ans:"T",
            exp:"用整個基因組當 background 會虛高 enrichment p-value。正確的 universe 應該是分析中實際偵測到的基因集合。",
            exp_en:"Using the whole genome as background inflates enrichment p-values. The correct universe is genes actually detected in the analysis." },
          { type:"single",
            stem:"GSEA 要求輸入的 ranks 必須是？",
            stem_en:"GSEA requires the input ranks to be?",
            A:"未排序的隨機序列", A_en:"Unsorted random sequence",
            B:"按 stat / LFC 由高到低排序，且無 NA", B_en:"Sorted by stat / LFC descending, with no NAs",
            C:"按字母排序的 gene symbols", C_en:"Gene symbols sorted alphabetically",
            D:"按 padj 由小到大排序", D_en:"Sorted by padj ascending",
            ans:"B",
            exp:"GSEA 的 running enrichment score 仰賴正確排序。常用排序鍵是 DESeq2 的 stat 或 limma 的 t；排 padj 會喪失方向資訊。",
            exp_en:"GSEA's running enrichment score depends on correct ordering. Common keys: DESeq2 stat or limma t; padj loses direction." }
        ]
      },

      "Track 2：Spatial Transcriptomics": {
        "Spatial 1：平台與技術": [
          { type:"single",
            stem:"10x Visium 一個 spot 大約涵蓋多少細胞？",
            stem_en:"A 10x Visium spot covers approximately how many cells?",
            A:"1 個（亞細胞解析度）", A_en:"1 (sub-cellular)",
            B:"0.5 個", B_en:"0.5",
            C:"1-10 個", C_en:"1-10",
            D:"100 個以上", D_en:"100+",
            ans:"C",
            exp:"Visium spot 直徑 55 μm，依組織密度涵蓋 1-10 個細胞。所以 Visium 通常需要 deconvolution 拆細胞類型比例。",
            exp_en:"A Visium spot is 55 μm; depending on tissue, it covers 1–10 cells. Hence deconvolution is often needed." },
          { type:"single",
            stem:"下列何者屬於 imaging-based 空間轉錄組學技術？",
            stem_en:"Which is an imaging-based spatial platform?",
            A:"Visium", A_en:"Visium",
            B:"MERFISH", B_en:"MERFISH",
            C:"Slide-seq", C_en:"Slide-seq",
            D:"Stereo-seq", D_en:"Stereo-seq",
            ans:"B",
            exp:"MERFISH 為 multi-round combinatorial FISH 影像技術，屬 imaging-based。Visium / Slide-seq / Stereo-seq 都是 array-based（NGS 流程）。",
            exp_en:"MERFISH is multi-round combinatorial FISH (imaging-based). Visium / Slide-seq / Stereo-seq are array-based (NGS workflow)." },
          { type:"multi",
            stem:"下列哪些屬於 array-based 空間轉錄組學技術？（多選）",
            stem_en:"Which are array-based spatial platforms? (Multiple)",
            A:"Visium", A_en:"Visium",
            B:"Slide-seq", B_en:"Slide-seq",
            C:"Stereo-seq", C_en:"Stereo-seq",
            D:"Xenium", D_en:"Xenium",
            ans:["A","B","C"],
            exp:"Visium、Slide-seq、Stereo-seq 都是 barcoded oligo array。Xenium 為 10x 的 imaging-based 平台。",
            exp_en:"Visium, Slide-seq, and Stereo-seq use barcoded oligo arrays. Xenium is 10x's imaging-based platform." },
          { type:"single",
            stem:"以下何者最適合對「FFPE 樣本 + 亞細胞解析度」的需求？",
            stem_en:"Which best suits the need 'FFPE samples + sub-cellular resolution'?",
            A:"Visium V1（fresh frozen only）", A_en:"Visium V1 (fresh frozen only)",
            B:"Xenium", B_en:"Xenium",
            C:"Slide-seq", C_en:"Slide-seq",
            D:"Stereo-seq", D_en:"Stereo-seq",
            ans:"B",
            exp:"Xenium 為 imaging-based 平台，原生支援 FFPE 與 fresh frozen，提供亞細胞解析度。",
            exp_en:"Xenium is imaging-based, supports FFPE natively, and offers sub-cellular resolution." },
          { type:"tf",
            stem:"是非題：MERFISH 是 whole-transcriptome 全基因組空間轉錄組學。",
            stem_en:"True/False: MERFISH is a whole-transcriptome spatial method.",
            ans:"F",
            exp:"MERFISH 是 panel-based，常見 100-1000 基因 panel；非 whole transcriptome。要全轉錄組需用 Visium / Stereo-seq 等 array-based 平台。",
            exp_en:"MERFISH is panel-based (typically 100–1000 genes); not whole transcriptome. For whole-Tx use array-based platforms like Visium / Stereo-seq." },
          { type:"single",
            stem:"關於 Visium HD（2024 推出），下列敘述何者正確？",
            stem_en:"Which is correct about Visium HD (released 2024)?",
            A:"解析度 55 μm 與 Visium V1 相同", A_en:"Same 55 μm resolution as Visium V1",
            B:"2 μm bin 提供近似亞細胞解析度", B_en:"2 μm bins for near sub-cellular resolution",
            C:"只能跑 fresh frozen", C_en:"Only fresh frozen supported",
            D:"無 H&E 染色", D_en:"No H&E support",
            ans:"B",
            exp:"Visium HD 以 2 μm × 2 μm bin 鋪滿 capture area，名義上接近單細胞解析度（實際單細胞識別仍需配合分割演算法）。",
            exp_en:"Visium HD tiles the capture area with 2 μm × 2 μm bins, nominally near single-cell resolution (full single-cell requires segmentation)." },
          { type:"single",
            stem:"SpaceRanger 輸出的 <code>tissue_positions.csv</code> 主要記錄什麼？",
            stem_en:"What does SpaceRanger's <code>tissue_positions.csv</code> record?",
            A:"每個 spot 的 UMI 數", A_en:"UMI per spot",
            B:"spot 的像素座標與是否位於組織內", B_en:"Spot pixel coordinates and tissue inside/outside flag",
            C:"基因註釋", C_en:"Gene annotation",
            D:"染色資訊", D_en:"Staining info",
            ans:"B",
            exp:"tissue_positions.csv 含每個 barcode 的像素座標、in-tissue 旗標等，是空間視覺化的基礎。",
            exp_en:"tissue_positions.csv stores pixel coordinates and in-tissue flags per barcode — the foundation for spatial visualization." }
        ],
        "Spatial 2：Preprocessing": [
          { type:"single",
            stem:"空間樣本 QC 中，spot 上 <code>percent.mt</code> 異常高最可能代表？",
            stem_en:"In spatial QC, an abnormally high <code>percent.mt</code> at a spot most likely indicates?",
            A:"高度轉錄活性", A_en:"High transcriptional activity",
            B:"組織壞死 / ischemia 區域", B_en:"Necrotic / ischemic tissue region",
            C:"doublet", C_en:"doublet",
            D:"上皮細胞特徵", D_en:"Epithelial signature",
            ans:"B",
            exp:"如 scRNA，高 mt% 通常代表細胞死亡。在空間樣本上，高 mt% 區域常對應壞死或缺氧區。",
            exp_en:"Like scRNA, high mt% indicates cell death. In spatial samples, high-mt% regions often map to necrotic or ischemic areas." },
          { type:"tf",
            stem:"是非題：標準 Seurat 與 Scanpy 都有原生支援 Visium 資料載入。",
            stem_en:"True/False: Both Seurat and Scanpy natively support Visium loading.",
            ans:"T",
            exp:"Seurat 用 <code>Load10X_Spatial()</code>；Scanpy 用 <code>sc.read_visium()</code>。",
            exp_en:"Seurat: <code>Load10X_Spatial()</code>; Scanpy: <code>sc.read_visium()</code>." },
          { type:"single",
            stem:"下列何者不是空間樣本特有的 QC 指標？",
            stem_en:"Which is NOT a spatial-specific QC metric?",
            A:"Tissue coverage（組織覆蓋率）", A_en:"Tissue coverage",
            B:"housekeeping 基因的空間自相關", B_en:"Spatial autocorrelation of housekeeping genes",
            C:"nFeature per spot", C_en:"nFeature per spot",
            D:"BLAST hit 數", D_en:"BLAST hit count",
            ans:"D",
            exp:"BLAST hit 是序列比對結果，與空間 QC 無關。其餘三項都是空間樣本評估指標。",
            exp_en:"BLAST hit is for sequence search, unrelated to spatial QC. The others are spatial QC metrics." },
          { type:"single",
            stem:"以下何者最適合空間樣本資料的標準化？",
            stem_en:"Which is most suitable for normalizing spatial data?",
            A:"直接用 raw counts", A_en:"Use raw counts directly",
            B:"SCTransform 或 LogNormalize", B_en:"SCTransform or LogNormalize",
            C:"量化為 TPM 後做 PCA", C_en:"Convert to TPM, then PCA",
            D:"quantile normalization", D_en:"Quantile normalization",
            ans:"B",
            exp:"空間樣本標準化原理同 scRNA：SCTransform（變異穩定 GLM 殘差）或 LogNormalize 是主流。",
            exp_en:"Spatial normalization mirrors scRNA: SCTransform (variance-stabilized GLM residuals) or LogNormalize are standard." },
          { type:"tf",
            stem:"是非題：將 deconvolution 輸出的 cell-type 比例直接餵 DESeq2 做差異分析是合理的做法。",
            stem_en:"True/False: It is valid to feed deconvolution-output cell-type proportions directly into DESeq2 for DE analysis.",
            ans:"F",
            exp:"deconv 比例為 softmax 輸出，不是 raw counts，違反 DESeq2 的負二項假設。差異要在 cluster / region 層級進行。",
            exp_en:"Deconvolution outputs are softmax proportions, not raw counts — they violate DESeq2's NB assumption. Run DE at cluster / region level." }
        ],
        "Spatial 3：空間聚類與 SVG": [
          { type:"single",
            stem:"SVG (Spatially Variable Gene) 與 HVG (Highly Variable Gene) 最大差別是？",
            stem_en:"What primarily distinguishes SVG from HVG?",
            A:"SVG 一定在 cluster 中顯著", A_en:"SVG is always significant in a cluster",
            B:"SVG 表達量必定較高", B_en:"SVG must have higher expression",
            C:"SVG 變異具有空間結構，HVG 只看整體變異", C_en:"SVG variance has spatial structure; HVG looks at overall variance only",
            D:"SVG 用 t-test 找", D_en:"SVG is found via t-test",
            ans:"C",
            exp:"HVG 看的是「整體變異是否大」，SVG 強調「變異是否隨空間位置呈現結構性」。",
            exp_en:"HVG cares about overall variance magnitude; SVG emphasizes structured variance along spatial position." },
          { type:"single",
            stem:"Moran's I = 0.8 對應的空間結構是？",
            stem_en:"Moran's I = 0.8 corresponds to what kind of spatial pattern?",
            A:"隨機分佈", A_en:"Random",
            B:"棋盤式分散", B_en:"Checkerboard / dispersed",
            C:"強空間聚集／結構", C_en:"Strong spatial clustering / structure",
            D:"無法計算", D_en:"Uncomputable",
            ans:"C",
            exp:"Moran's I 接近 1 代表強空間自相關；接近 0 為隨機；負值為分散（棋盤）。",
            exp_en:"Moran's I near 1 = strong spatial autocorrelation; near 0 = random; negative = dispersed (checkerboard)." },
          { type:"multi",
            stem:"下列哪些是 spatial-aware clustering 工具？（多選）",
            stem_en:"Which are spatial-aware clustering tools? (Multiple)",
            A:"BayesSpace", A_en:"BayesSpace",
            B:"Banksy", B_en:"Banksy",
            C:"SpaGCN", C_en:"SpaGCN",
            D:"DESeq2", D_en:"DESeq2",
            ans:["A","B","C"],
            exp:"前三者是 spatial-aware 工具，會在 cluster 過程中考量鄰近資訊。DESeq2 是 DE 工具。",
            exp_en:"The first three are spatial-aware clustering tools using neighbor information; DESeq2 is a DE tool." },
          { type:"single",
            stem:"哪個 SVG 偵測工具最適合大型空間資料集（&gt; 100k spots）的記憶體效率需求？",
            stem_en:"Which SVG tool is best suited for large spatial datasets (&gt; 100k spots) needing memory efficiency?",
            A:"SpatialDE", A_en:"SpatialDE",
            B:"SPARK", B_en:"SPARK",
            C:"SPARK-X", C_en:"SPARK-X",
            D:"基本 t-test", D_en:"Basic t-test",
            ans:"C",
            exp:"SPARK-X 為 SPARK 的可擴充版本，針對大資料集設計；SpatialDE/SPARK 在大資料時計算成本高。",
            exp_en:"SPARK-X is the scalable successor of SPARK; SpatialDE / SPARK become expensive for large data." },
          { type:"tf",
            stem:"是非題：BayesSpace 可進行 sub-spot 解析度增強，超越原本 Visium spot 解析度。",
            stem_en:"True/False: BayesSpace can perform sub-spot resolution enhancement, exceeding the original Visium spot resolution.",
            ans:"T",
            exp:"BayesSpace 將每個 spot 細分為 6-7 個 sub-spots，以 HMM 推估其表達，是其特色功能之一。",
            exp_en:"BayesSpace subdivides each spot into 6-7 sub-spots and infers expression via HMM — a signature feature." },
          { type:"single",
            stem:"在 squidpy 中計算 Moran's I 前，必須先做的步驟是？",
            stem_en:"Before computing Moran's I in squidpy, what step is required first?",
            A:"PCA 降維", A_en:"PCA dimensionality reduction",
            B:"建立 spatial neighbor graph (<code>sq.gr.spatial_neighbors</code>)", B_en:"Build the spatial neighbor graph (<code>sq.gr.spatial_neighbors</code>)",
            C:"執行 DESeq2", C_en:"Run DESeq2",
            D:"做 doublet detection", D_en:"Run doublet detection",
            ans:"B",
            exp:"Moran's I 計算依賴 spot 鄰接圖；squidpy 中要先用 <code>sq.gr.spatial_neighbors()</code> 建立。",
            exp_en:"Moran's I depends on a spot adjacency graph; in squidpy build it first with <code>sq.gr.spatial_neighbors()</code>." }
        ],
        "Spatial 4：Deconvolution": [
          { type:"single",
            stem:"Visium spot deconvolution 的主要輸入是？",
            stem_en:"What is the primary input for Visium spot deconvolution?",
            A:"只用 Visium 表達矩陣", A_en:"Visium expression matrix only",
            B:"Visium spot × gene 矩陣 + 同組織的單細胞 reference", B_en:"Visium spot × gene matrix + single-cell reference of the same tissue",
            C:"只用 H&E 影像", C_en:"H&E image only",
            D:"基因組 BAM", D_en:"Genome BAM",
            ans:"B",
            exp:"deconvolution 工具（cell2location、RCTD、CARD 等）需要 spatial 表達矩陣 + 該組織的 scRNA reference。",
            exp_en:"Tools (cell2location, RCTD, CARD) need both the spatial expression matrix and a scRNA reference of the same tissue." },
          { type:"single",
            stem:"下列何者特別強調「估計每 spot 的絕對細胞數」？",
            stem_en:"Which tool emphasizes 'estimating absolute cell counts per spot'?",
            A:"SPOTlight", A_en:"SPOTlight",
            B:"cell2location", B_en:"cell2location",
            C:"Tangram", C_en:"Tangram",
            D:"CARD", D_en:"CARD",
            ans:"B",
            exp:"cell2location 為 hierarchical Poisson 模型，估計每個 spot 中每種 cell type 的絕對細胞數而非僅相對比例。",
            exp_en:"cell2location uses a hierarchical Poisson model to estimate absolute cell counts per cell type per spot, not just proportions." },
          { type:"multi",
            stem:"下列哪些是 Visium spot deconvolution 工具？（多選）",
            stem_en:"Which are Visium spot deconvolution tools? (Multiple)",
            A:"cell2location", A_en:"cell2location",
            B:"RCTD", B_en:"RCTD",
            C:"SPOTlight", C_en:"SPOTlight",
            D:"GATK", D_en:"GATK",
            ans:["A","B","C"],
            exp:"前三者皆是 deconvolution 工具；GATK 是變異偵測工具。",
            exp_en:"The first three are deconvolution tools; GATK is for variant calling." },
          { type:"tf",
            stem:"是非題：用「肺組織的 scRNA reference」對「腎組織的 Visium 樣本」做 deconvolution 是合理且通常可行的。",
            stem_en:"True/False: Using a lung scRNA reference to deconvolute a kidney Visium sample is reasonable and usually works.",
            ans:"F",
            exp:"deconvolution 高度依賴 cell-type signatures。Reference 與 spatial 樣本必須來自同組織（或極近緣的組織）。",
            exp_en:"Deconvolution depends heavily on cell-type signatures. Reference and spatial sample must come from the same (or very similar) tissue." },
          { type:"single",
            stem:"關於 deconvolution reference 註釋粒度，下列敘述何者正確？",
            stem_en:"Regarding annotation granularity of the deconvolution reference, which is correct?",
            A:"註釋越粗越好（如全部歸為 \"immune cell\"）", A_en:"Coarser is better (e.g., all labeled 'immune cell')",
            B:"註釋粒度應該對應分析目的；過粗會喪失子型別資訊", B_en:"Granularity should match the analysis goal; too coarse loses subtype info",
            C:"必須包含所有可能 cell type 的 100k+ 細胞", C_en:"Must include 100k+ cells of every possible type",
            D:"reference 不影響結果", D_en:"Reference doesn't affect results",
            ans:"B",
            exp:"註釋粒度決定 deconvolution 能解析到的細胞層級。想看 CD4 / CD8 / Treg 子群需精細註釋；只關心 immune vs stroma 可粗註釋。",
            exp_en:"Annotation granularity sets the resolution of deconvolution. CD4 / CD8 / Treg distinctions need fine labels; coarse labels suffice for immune-vs-stroma questions." }
        ],
        "Spatial 5：細胞通訊": [
          { type:"single",
            stem:"標準 scRNA-seq 級的 CellChat 在做空間樣本通訊分析時，最大的限制是？",
            stem_en:"What is the biggest limitation of using scRNA-level CellChat on spatial samples?",
            A:"找不到 ligand-receptor pair", A_en:"Can't find ligand-receptor pairs",
            B:"假設「任何兩種 cell type 共表達 L-R 即可通訊」，忽略距離", B_en:"Assumes any two cell types co-expressing L-R can communicate, ignoring distance",
            C:"速度太慢", C_en:"Too slow",
            D:"不支援人類資料", D_en:"Doesn't support human data",
            ans:"B",
            exp:"CellChat / CellPhoneDB 屬非空間感知工具；對 paracrine 訊號的「物理距離」沒有限制，故對空間樣本不夠精準。",
            exp_en:"CellChat / CellPhoneDB are not spatial-aware; without distance constraints, paracrine inferences may be unreliable on spatial data." },
          { type:"single",
            stem:"COMMOT 的核心數學工具是？",
            stem_en:"What mathematical tool underlies COMMOT?",
            A:"hidden Markov model", A_en:"Hidden Markov model",
            B:"optimal transport", B_en:"Optimal transport",
            C:"PageRank", C_en:"PageRank",
            D:"k-means", D_en:"k-means",
            ans:"B",
            exp:"COMMOT 用 collective optimal transport 估計細胞間的訊號傳輸方向與量。",
            exp_en:"COMMOT uses collective optimal transport to infer the direction and magnitude of cell-cell signaling flow." },
          { type:"single",
            stem:"通常 paracrine 訊號的典型距離尺度是？",
            stem_en:"What is the typical distance scale of paracrine signaling?",
            A:"1 μm 以內", A_en:"Within 1 μm",
            B:"50-200 μm", B_en:"50–200 μm",
            C:"&gt; 1 cm", C_en:"&gt; 1 cm",
            D:"無限遠（全身）", D_en:"Unlimited (systemic)",
            ans:"B",
            exp:"juxtacrine ~ 10-20 μm（細胞接觸）；paracrine ~ 50-200 μm；endocrine 為跨組織。空間細胞通訊分析常用 σ ≈ 50-150 μm。",
            exp_en:"Juxtacrine ~10–20 μm; paracrine ~50–200 μm; endocrine is systemic. Spatial CCC analyses commonly use σ ≈ 50–150 μm." },
          { type:"tf",
            stem:"是非題：在空間通訊分析中，將 spot 位置隨機 shuffle 後若仍偵測到顯著的 LR 對，代表結果非真實空間驅動。",
            stem_en:"True/False: If shuffled spot positions still produce significant LR pairs in spatial CCC, results are not spatially driven.",
            ans:"T",
            exp:"shuffle 後仍顯著代表訊號來自 cell type 共表達而非空間鄰近——這是有效的負控制檢驗。",
            exp_en:"Persistent signal after shuffling indicates the result reflects co-expression, not spatial proximity — a valid negative control." }
        ]
      },

      "Track 3：ATAC-seq / Epigenomics": {
        "ATAC 1：原理與片段分佈": [
          { type:"single",
            stem:"ATAC-seq 片段直方圖中 ~180 bp 與 ~360 bp 峰最合理的解釋是？",
            stem_en:"What best explains the ~180 bp and ~360 bp peaks in the ATAC-seq fragment histogram?",
            A:"PCR 偏好 ~180 bp", A_en:"PCR prefers ~180 bp",
            B:"Tn5 不能切核小體保護的 DNA，片段大小反映被核小體保護的長度", B_en:"Tn5 cannot cut nucleosome-protected DNA; sizes reflect protected lengths",
            C:"接頭設計為 180 bp", C_en:"Adapter is 180 bp",
            D:"是 PCR 重複", D_en:"PCR duplicates",
            ans:"B",
            exp:"180 bp ≈ 一個核小體（147 bp + linker）；360 bp ≈ 兩個核小體。Tn5 切位避開核小體保護區，留下這些特徵長度。",
            exp_en:"180 bp ≈ one nucleosome (147 bp + linker); 360 bp ≈ two. Tn5 avoids nucleosome-protected regions, leaving these characteristic lengths." },
          { type:"single",
            stem:"ATAC-seq 比對後必須做的「+4 / -5 shift」目的是？",
            stem_en:"Why is the '+4 / -5 shift' mandatory after ATAC-seq alignment?",
            A:"修正測序錯誤", A_en:"Correct sequencing errors",
            B:"校正 Tn5 二聚體 9 bp 黏端造成的切位偏差", B_en:"Correct for the 9 bp Tn5 dimer staggered cut",
            C:"修正接頭汙染", C_en:"Fix adapter contamination",
            D:"提升 mapping rate", D_en:"Improve mapping rate",
            ans:"B",
            exp:"Tn5 二聚體切位形成 9 bp 黏端；forward read 起點應 +4、reverse 應 -5 才回到真正的開放邊界。",
            exp_en:"Tn5 dimer creates a 9-bp staggered cut; forward starts shift +4 and reverse -5 to recover the true open boundary." },
          { type:"single",
            stem:"ATAC-seq 樣本中粒線體 DNA reads 通常佔比為？",
            stem_en:"What fraction of ATAC-seq reads is typically mitochondrial DNA?",
            A:"&lt; 1%", A_en:"&lt; 1%",
            B:"1-5%", B_en:"1–5%",
            C:"30-50%", C_en:"30–50%",
            D:"&gt; 90%", D_en:"&gt; 90%",
            ans:"C",
            exp:"粒線體 DNA 完全開放，可被 Tn5 高效切。傳統 ATAC 中 chrM 常佔 30-50% reads，是 omni-ATAC 改良要解決的問題之一。",
            exp_en:"Mitochondrial DNA is fully accessible, so Tn5 cuts it efficiently. Classical ATAC often has 30–50% chrM reads — a target of the omni-ATAC improvement." },
          { type:"tf",
            stem:"是非題：ATAC-seq 與 ChIP-seq 的主要差別是 ATAC 偵測「開放染色質」，ChIP-seq 偵測「特定蛋白結合位」。",
            stem_en:"True/False: The main difference between ATAC-seq and ChIP-seq is that ATAC detects 'open chromatin' while ChIP-seq detects 'specific protein binding sites'.",
            ans:"T",
            exp:"ATAC-seq 不需抗體，全基因組性偵測 OCR；ChIP-seq 用抗體富集特定 TF / 組蛋白修飾的結合 DNA。",
            exp_en:"ATAC-seq is antibody-free and surveys OCRs genome-wide; ChIP-seq uses antibodies to enrich DNA bound by a specific TF / histone mark." },
          { type:"multi",
            stem:"下列哪些是 ATAC-seq 預處理流程的標準步驟？（多選）",
            stem_en:"Which are standard steps in ATAC-seq preprocessing? (Multiple)",
            A:"+4 / -5 shift", A_en:"+4 / -5 shift",
            B:"移除 chrM reads", B_en:"Remove chrM reads",
            C:"移除 ENCODE blacklist 區域", C_en:"Remove ENCODE blacklist regions",
            D:"做 PCA 降維", D_en:"Run PCA",
            ans:["A","B","C"],
            exp:"前三者是 ATAC 預處理必備。PCA 是下游分析步驟，與預處理無關。",
            exp_en:"The first three are essential ATAC preprocessing steps. PCA is downstream analysis, not preprocessing." },
          { type:"single",
            stem:"關於 omni-ATAC（Corces 2017），下列敘述何者正確？",
            stem_en:"Which is correct about omni-ATAC (Corces 2017)?",
            A:"取代 ATAC-seq 成為唯一可用流程", A_en:"Replaces ATAC-seq as the only usable protocol",
            B:"改良 ATAC 化學流程，降低 chrM 比例並支援冷凍組織", B_en:"Refined ATAC chemistry that lowers chrM ratio and supports frozen tissues",
            C:"只能用於小鼠樣本", C_en:"Only works for mouse samples",
            D:"不需 Tn5", D_en:"Doesn't use Tn5",
            ans:"B",
            exp:"omni-ATAC 透過去 chrM 步驟與條件優化，降低背景並擴展至冷凍 / FFPE 組織。",
            exp_en:"omni-ATAC introduces a chrM-depletion step and protocol tweaks, reducing background and extending to frozen / FFPE tissues." }
        ],
        "ATAC 2：Alignment 與 Peak Calling": [
          { type:"single",
            stem:"ENCODE 推薦 ATAC-seq 比對用什麼工具與設定？",
            stem_en:"Which tool and setting does ENCODE recommend for ATAC-seq alignment?",
            A:"Bowtie2 --very-sensitive", A_en:"Bowtie2 --very-sensitive",
            B:"STAR --twoPassMode", B_en:"STAR --twoPassMode",
            C:"Salmon", C_en:"Salmon",
            D:"BLAST", D_en:"BLAST",
            ans:"A",
            exp:"ENCODE ATAC-seq pipeline 標準使用 Bowtie2 with <code>--very-sensitive -X 2000</code>。",
            exp_en:"ENCODE's ATAC-seq pipeline uses Bowtie2 with <code>--very-sensitive -X 2000</code>." },
          { type:"single",
            stem:"MACS2 / MACS3 對 ATAC paired-end 樣本推薦的關鍵設定是？",
            stem_en:"What is the key MACS2 / MACS3 setting for ATAC paired-end samples?",
            A:"<code>-f BAM</code>（默認）", A_en:"<code>-f BAM</code> (default)",
            B:"<code>-f BAMPE --nomodel --shift -75 --extsize 150</code>", B_en:"<code>-f BAMPE --nomodel --shift -75 --extsize 150</code>",
            C:"<code>--broad</code> 必須加", C_en:"<code>--broad</code> is mandatory",
            D:"<code>--single-end-only</code>", D_en:"<code>--single-end-only</code>",
            ans:"B",
            exp:"<code>-f BAMPE</code> 啟用 paired-end 模式；<code>--nomodel --shift -75 --extsize 150</code> 是 ATAC 標準（覆蓋 Tn5 切位）。",
            exp_en:"<code>-f BAMPE</code> enables paired-end mode; <code>--nomodel --shift -75 --extsize 150</code> is the ATAC standard (covering Tn5 cut sites)." },
          { type:"single",
            stem:"ATAC-seq 最重要的單一 QC 指標是？",
            stem_en:"What is the single most important QC metric for ATAC-seq?",
            A:"PCR duplication rate", A_en:"PCR duplication rate",
            B:"TSS Enrichment Score", B_en:"TSS Enrichment Score",
            C:"% mapped to genome", C_en:"% mapped to genome",
            D:"insert size variance", D_en:"Insert size variance",
            ans:"B",
            exp:"TSS Enrichment 反映訊號集中於開放區的程度。&gt; 7 為高品質、5-7 可接受、&lt; 5 低品質。",
            exp_en:"TSS Enrichment reflects how well the signal concentrates at open regions. &gt;7 high, 5–7 OK, &lt;5 low quality." },
          { type:"single",
            stem:"FRiP（Fraction of Reads in Peaks）的 ENCODE 建議門檻是？",
            stem_en:"What is ENCODE's recommended FRiP threshold?",
            A:"&gt; 0.05", A_en:"&gt; 0.05",
            B:"&gt; 0.2-0.3（acceptable / ideal）", B_en:"&gt; 0.2-0.3 (acceptable / ideal)",
            C:"&gt; 0.9", C_en:"&gt; 0.9",
            D:"不需檢查", D_en:"No need to check",
            ans:"B",
            exp:"ENCODE 標準 FRiP &gt; 0.2 為 acceptable、&gt; 0.3 為 ideal。",
            exp_en:"ENCODE standard: FRiP &gt; 0.2 is acceptable, &gt; 0.3 is ideal." },
          { type:"tf",
            stem:"是非題：Genrich 是專為 ATAC-seq 設計的 peak caller，不需手動 +4 / -5 shift。",
            stem_en:"True/False: Genrich is an ATAC-specific peak caller that does not require manual +4 / -5 shifting.",
            ans:"T",
            exp:"Genrich 加 <code>-j</code> 旗標即可進入 ATAC 模式，內建 shift 與多重訊號處理。",
            exp_en:"Genrich enters ATAC mode with <code>-j</code>; shift and multi-mapper logic are built in." },
          { type:"single",
            stem:"差異開放區域（DAR）分析常用的 R 套件是？",
            stem_en:"Which R package is common for differential accessibility region (DAR) analysis?",
            A:"DESeq2 only", A_en:"DESeq2 only",
            B:"DiffBind", B_en:"DiffBind",
            C:"limma 不能用於 ATAC", C_en:"limma cannot be used on ATAC",
            D:"GATK", D_en:"GATK",
            ans:"B",
            exp:"DiffBind 整合 peak union、計數、normalization 與 DE 比較，是 ATAC / ChIP DAR 分析最普及的工具。",
            exp_en:"DiffBind integrates peak union, counting, normalization, and DE — the most widely used DAR tool for ATAC / ChIP." }
        ],
        "ATAC 3：Motif 與 Footprinting": [
          { type:"single",
            stem:"Motif enrichment 與 footprinting 最主要的差別是？",
            stem_en:"What is the main difference between motif enrichment and footprinting?",
            A:"Motif enrichment 偵測 TF 是否真的結合；footprinting 只看 motif 存在", A_en:"Motif enrichment detects actual binding; footprinting only checks motif presence",
            B:"Motif enrichment 看 motif 是否富集於 peaks；footprinting 看 motif 上是否有 TF 蹲坐造成的 cut-signal 下凹", B_en:"Motif enrichment tests motif over-representation in peaks; footprinting checks whether a TF actually sits on the motif, leaving a cut-signal dip",
            C:"兩者完全相同", C_en:"They are identical",
            D:"Footprinting 是 motif enrichment 的快速版", D_en:"Footprinting is a faster version of motif enrichment",
            ans:"B",
            exp:"motif enrichment 問「我的 peaks 富集哪些 TF 的序列模式」；footprinting 進一步問「該 motif 上是否真有 TF 蛋白蹲坐」（從 cut signal 凹陷判斷）。",
            exp_en:"Enrichment asks 'which TF motifs are over-represented in my peaks'; footprinting asks 'is a TF actually bound at this motif' (inferred from a dip in cut signal)." },
          { type:"single",
            stem:"HOMER 的 <code>findMotifsGenome.pl</code> 主要功能是？",
            stem_en:"What does HOMER's <code>findMotifsGenome.pl</code> primarily do?",
            A:"從基因組 FASTA 找新 motif", A_en:"Find novel motifs in genome FASTA",
            B:"對輸入的 peak BED 做 known + de novo motif enrichment", B_en:"Perform known + de novo motif enrichment on input peak BED",
            C:"做變異註釋", C_en:"Annotate variants",
            D:"建立 BWA 索引", D_en:"Build BWA index",
            ans:"B",
            exp:"<code>findMotifsGenome.pl</code> 對 peak BED 輸入做 known motif 富集檢定與 de novo motif 發現。",
            exp_en:"<code>findMotifsGenome.pl</code> performs known motif enrichment and de novo motif discovery on a peak BED." },
          { type:"multi",
            stem:"下列哪些工具屬於 ATAC-seq footprinting 範疇？（多選）",
            stem_en:"Which tools belong to ATAC-seq footprinting? (Multiple)",
            A:"HINT-ATAC", A_en:"HINT-ATAC",
            B:"TOBIAS", B_en:"TOBIAS",
            C:"Wellington", C_en:"Wellington",
            D:"BWA", D_en:"BWA",
            ans:["A","B","C"],
            exp:"HINT-ATAC、TOBIAS、Wellington 都是 footprinting 工具。BWA 是 aligner。",
            exp_en:"HINT-ATAC, TOBIAS, and Wellington are footprinting tools. BWA is an aligner." },
          { type:"tf",
            stem:"是非題：motif enrichment 顯著代表「該 TF 真的在 peaks 中結合」。",
            stem_en:"True/False: Significant motif enrichment proves the TF is truly bound at those peaks.",
            ans:"F",
            exp:"enrichment 只說「peaks 有該 TF 的 motif」；要證明 binding，需 footprinting 或 ChIP-seq。",
            exp_en:"Enrichment only shows 'the motif is present in peaks'; proving binding requires footprinting or ChIP-seq." },
          { type:"single",
            stem:"chromVAR 主要用於什麼情境？",
            stem_en:"chromVAR is mainly used for what?",
            A:"bulk ATAC peak calling", A_en:"Bulk ATAC peak calling",
            B:"單細胞 ATAC（scATAC）motif accessibility 分析", B_en:"Single-cell ATAC (scATAC) motif accessibility analysis",
            C:"RNA-seq DE", C_en:"RNA-seq DE",
            D:"VCF annotation", D_en:"VCF annotation",
            ans:"B",
            exp:"chromVAR 計算每個細胞每個 motif 的 deviation score，是 scATAC 主流 motif 分析工具。",
            exp_en:"chromVAR computes per-cell, per-motif deviation scores — the leading scATAC motif tool." },
          { type:"single",
            stem:"以下哪個資料庫提供 TF binding profile（PWM）供 motif 分析使用？",
            stem_en:"Which database provides TF binding profiles (PWMs) for motif analysis?",
            A:"JASPAR", A_en:"JASPAR",
            B:"gnomAD", B_en:"gnomAD",
            C:"ClinVar", C_en:"ClinVar",
            D:"recount3", D_en:"recount3",
            ans:"A",
            exp:"JASPAR 是公開的 TF binding profile 資料庫；CIS-BP 是另一個常用來源。",
            exp_en:"JASPAR is the public TF binding profile database; CIS-BP is another common source." }
        ],
        "ATAC 4：多體學整合": [
          { type:"single",
            stem:"10x Multiome 的特點是？",
            stem_en:"What characterizes 10x Multiome?",
            A:"同一細胞同時測 RNA 與 ATAC", A_en:"Same cell measured for both RNA and ATAC",
            B:"只能用於小鼠", B_en:"Only mouse",
            C:"測序成本最低", C_en:"Cheapest sequencing",
            D:"不需要單細胞分離", D_en:"No single-cell isolation needed",
            ans:"A",
            exp:"10x Multiome 在同一個細胞同時量測 RNA 與 ATAC，可直接計算 peak-gene 跨細胞相關。",
            exp_en:"10x Multiome captures RNA and ATAC in the same cell, enabling direct cross-cell peak-gene correlation." },
          { type:"multi",
            stem:"下列哪些是 peak-to-gene 連結的常見策略？（多選）",
            stem_en:"Which are common strategies for peak-to-gene linking? (Multiple)",
            A:"基於距離（peak 對 ±100 kb 內的 TSS）", A_en:"Distance-based (peak to TSS within ±100 kb)",
            B:"基於相關性（scMultiome 跨細胞 correlation）", B_en:"Correlation-based (scMultiome cross-cell correlation)",
            C:"基於 3D 染色質接觸資料（Hi-C / HiChIP）", C_en:"3D contact-based (Hi-C / HiChIP)",
            D:"基於基因縮寫字母順序", D_en:"Based on gene symbol alphabet",
            ans:["A","B","C"],
            exp:"距離、相關性、3D 接觸都是有效策略；字母順序顯然無生物學意義。",
            exp_en:"Distance, correlation, and 3D contacts are valid strategies; alphabet is biologically meaningless." },
          { type:"single",
            stem:"Signac 與 ArchR 都屬於哪一類工具？",
            stem_en:"Signac and ArchR both belong to which category?",
            A:"bulk RNA-seq DE 工具", A_en:"Bulk RNA-seq DE tools",
            B:"scATAC / scMultiome 整合分析工具", B_en:"scATAC / scMultiome integrative analysis tools",
            C:"VCF 處理工具", C_en:"VCF utilities",
            D:"組裝工具", D_en:"Assembly tools",
            ans:"B",
            exp:"Signac（Seurat 生態系）與 ArchR 都是 scATAC / scMultiome 分析平台；ArchR 對大資料更友好。",
            exp_en:"Signac (Seurat ecosystem) and ArchR both target scATAC / scMultiome; ArchR scales better to large data." },
          { type:"tf",
            stem:"是非題：在沒有 scMultiome 配對資料時，仍可用 GLUE 等工具整合「不同細胞的 RNA 與 ATAC」到共同 embedding。",
            stem_en:"True/False: Without paired scMultiome data, tools like GLUE can integrate 'RNA and ATAC from different cells' into a joint embedding.",
            ans:"T",
            exp:"GLUE 等 unpaired 整合工具透過 graph-linked embedding 將不同模態的細胞投射到共空間。",
            exp_en:"GLUE-style unpaired integration uses graph-linked embeddings to project cells from different modalities into a shared space." }
        ]
      },

      "Track 4：Variant Calling (WGS/WES)": {
        "Variant 1：Read 預處理": [
          { type:"single",
            stem:"BWA-MEM 跑 paired-end 比對時，下列哪個 metadata 是 GATK 後續步驟必填？",
            stem_en:"Which metadata is mandatory for downstream GATK steps after BWA-MEM paired-end alignment?",
            A:"barcode", A_en:"barcode",
            B:"ReadGroup (RG) 含 ID/SM/LB/PL", B_en:"ReadGroup (RG) with ID/SM/LB/PL",
            C:"insert size only", C_en:"Insert size only",
            D:"沒有任何 metadata 需要", D_en:"No metadata required",
            ans:"B",
            exp:"GATK 透過 ReadGroup 識別樣本身份。漏 RG 會在 HaplotypeCaller / Mutect2 等步驟錯誤。",
            exp_en:"GATK uses ReadGroup to identify samples. Missing RG breaks HaplotypeCaller / Mutect2 etc." },
          { type:"single",
            stem:"MarkDuplicates 主要解決 RNA-seq / DNA-seq 哪一類問題？",
            stem_en:"What problem does MarkDuplicates primarily solve?",
            A:"接頭汙染", A_en:"Adapter contamination",
            B:"PCR / optical duplicate 灌水 allele depth", B_en:"PCR / optical duplicates inflating allele depth",
            C:"strand bias", C_en:"strand bias",
            D:"GC bias", D_en:"GC bias",
            ans:"B",
            exp:"PCR / optical duplicate 為同一原始分子的多份複製，若不標記會造成 allele depth 過度自信、產生假陽性。",
            exp_en:"PCR / optical duplicates are copies of one molecule; without marking, allele depth is over-confident and yields false positives." },
          { type:"single",
            stem:"BQSR 的核心思想是？",
            stem_en:"What is the core idea of BQSR?",
            A:"重新訓練 read aligner", A_en:"Retrain the read aligner",
            B:"用 dbSNP 等已知 SNP 作為「正確」訓練集，學習機器偏差後校正 Phred 分數", B_en:"Use known SNPs (dbSNP) as ground truth to learn machine bias and recalibrate Phred scores",
            C:"刪除 PCR duplicate", C_en:"Remove PCR duplicates",
            D:"重新做 trimming", D_en:"Redo trimming",
            ans:"B",
            exp:"BQSR 假設「已知 SNP 以外的位置應為 reference 一致」，藉此估計 base quality 偏差並校正。",
            exp_en:"BQSR assumes 'sites outside known SNPs should match reference', estimating base-quality bias and recalibrating." },
          { type:"multi",
            stem:"下列哪些是 GATK Best Practice 中 \"analysis-ready BAM\" 的必要前處理步驟？（多選）",
            stem_en:"Which are required preprocessing steps for an 'analysis-ready BAM' in GATK Best Practice? (Multiple)",
            A:"BWA-MEM 比對 + ReadGroup", A_en:"BWA-MEM alignment + ReadGroup",
            B:"MarkDuplicates", B_en:"MarkDuplicates",
            C:"BQSR (BaseRecalibrator + ApplyBQSR)", C_en:"BQSR (BaseRecalibrator + ApplyBQSR)",
            D:"PCA on BAM", D_en:"PCA on BAM",
            ans:["A","B","C"],
            exp:"GATK BP 三步：BWA-MEM → MarkDuplicates → BQSR。PCA on BAM 不存在。",
            exp_en:"GATK BP three steps: BWA-MEM → MarkDuplicates → BQSR. 'PCA on BAM' does not exist." },
          { type:"tf",
            stem:"是非題：人類 germline WGS 樣本建議 unique coverage 至少 30×。",
            stem_en:"True/False: Human germline WGS samples typically require ≥ 30× unique coverage.",
            ans:"T",
            exp:"30× unique 是 germline WGS 的業界標準，提供約 99% 異型合子 (heterozygous) 變異的偵測力。",
            exp_en:"30× unique is the WGS industry standard, yielding ~99% heterozygous variant detection power." },
          { type:"single",
            stem:"以下哪個情境 BQSR 最可能<strong>不</strong>需要？",
            stem_en:"In which scenario is BQSR LEAST necessary?",
            A:"人類 30× WGS 標準分析", A_en:"Standard human 30× WGS",
            B:"無已知 SNP 資料庫的非模式物種", B_en:"Non-model organism without a known-SNP database",
            C:"癌症體細胞變異偵測", C_en:"Cancer somatic variant calling",
            D:"GATK Best Practice germline", D_en:"GATK Best Practice germline",
            ans:"B",
            exp:"BQSR 需「已知變異」訓練集；對無資料庫的非模式物種無法跑或結果可疑，常以 bootstrap BQSR 替代。",
            exp_en:"BQSR needs a known-variant training set; for non-model organisms without one, BQSR may not run or yield unreliable results — bootstrap BQSR is an alternative." }
        ],
        "Variant 2：Variant Calling": [
          { type:"single",
            stem:"germline 變異與 somatic 變異最主要的差別是？",
            stem_en:"What is the main difference between germline and somatic variants?",
            A:"germline 為實驗誤差，somatic 為真實", A_en:"Germline is experimental error; somatic is real",
            B:"germline 全身細胞共有，VAF 預期 0%/50%/100%；somatic 為後天產生，VAF 連續分佈", B_en:"Germline is shared by all cells with expected VAF 0/50/100%; somatic is acquired with continuous VAF",
            C:"兩者完全相同", C_en:"They are identical",
            D:"germline 只在血液", D_en:"Germline is only in blood",
            ans:"B",
            exp:"germline 為遺傳變異，所有細胞共有；somatic 為癌症等後天突變，常有亞群體性，VAF 可能很低。",
            exp_en:"Germline is inherited and shared by all cells; somatic is acquired (e.g., cancer) and often subclonal, with low VAF possible." },
          { type:"single",
            stem:"GATK Mutect2 的「PoN」(Panel of Normals) 主要用途是？",
            stem_en:"What is the main purpose of GATK Mutect2's 'PoN' (Panel of Normals)?",
            A:"取代 dbSNP", A_en:"Replace dbSNP",
            B:"過濾在多個正常樣本中也出現的假陽性 / 技術 artifact", B_en:"Filter false positives / technical artifacts seen in many normal samples",
            C:"提升真實腫瘤變異 sensitivity", C_en:"Boost true tumor variant sensitivity",
            D:"做基因組組裝", D_en:"For genome assembly",
            ans:"B",
            exp:"PoN 收集多個正常樣本的雜訊位置（如 alignment artifact），把它們從 Mutect2 結果中過濾掉。",
            exp_en:"PoN collects noisy positions (alignment artifacts) from many normals to filter them from Mutect2 outputs." },
          { type:"single",
            stem:"DeepVariant 的核心方法是？",
            stem_en:"What is the core method of DeepVariant?",
            A:"傳統 likelihood model", A_en:"Traditional likelihood model",
            B:"把比對 pileup 轉成影像，用 CNN 分類為 ref/het/hom", B_en:"Convert pileup to an image and classify ref/het/hom with a CNN",
            C:"Bayesian network", C_en:"Bayesian network",
            D:"hidden Markov model", D_en:"Hidden Markov model",
            ans:"B",
            exp:"DeepVariant 把每個候選位點的 pileup 視為影像，用 CNN 分類；在 GIAB benchmark 上常有業界領先準確度。",
            exp_en:"DeepVariant treats each candidate pileup as an image classified by a CNN, achieving state-of-the-art accuracy on GIAB benchmarks." },
          { type:"multi",
            stem:"下列哪些是常見的 germline 變異偵測工具？（多選）",
            stem_en:"Which are common germline variant callers? (Multiple)",
            A:"GATK HaplotypeCaller", A_en:"GATK HaplotypeCaller",
            B:"DeepVariant", B_en:"DeepVariant",
            C:"Strelka2", C_en:"Strelka2",
            D:"BWA-MEM", D_en:"BWA-MEM",
            ans:["A","B","C"],
            exp:"前三者是 germline caller；BWA-MEM 是 aligner。",
            exp_en:"The first three are germline callers; BWA-MEM is an aligner." },
          { type:"tf",
            stem:"是非題：在多樣本族群分析中，GATK Best Practice 推薦每樣本先產生 GVCF，再用 GenotypeGVCFs 進行 joint genotyping。",
            stem_en:"True/False: For multi-sample cohorts, GATK BP recommends generating GVCFs per sample, then joint genotyping with GenotypeGVCFs.",
            ans:"T",
            exp:"這是 GATK BP 的標準流程：每樣本 HaplotypeCaller -ERC GVCF 後集中 GenotypeGVCFs，確保 ref-ref 位點被正確記錄。",
            exp_en:"This is the GATK BP standard: per-sample HaplotypeCaller -ERC GVCF then GenotypeGVCFs ensures ref-ref sites are recorded correctly." },
          { type:"single",
            stem:"癌症腫瘤樣本中常見的 VAF（變異等位基因頻率）分佈特徵是？",
            stem_en:"What is typical for VAF distribution in cancer tumor samples?",
            A:"只有 0%、50%、100% 三種值", A_en:"Only three values: 0%, 50%, 100%",
            B:"連續分佈，常因 subclonality 出現 5-30% 等中低 VAF", B_en:"Continuous distribution; subclonality often produces low-intermediate VAFs (5–30%)",
            C:"所有變異 VAF = 100%", C_en:"All variants have VAF = 100%",
            D:"VAF 與深度無關", D_en:"VAF is independent of depth",
            ans:"B",
            exp:"腫瘤中 subclone 比例造成連續 VAF。低 VAF 變異需高深度 + 體細胞專用 caller 才能偵測。",
            exp_en:"Subclonality produces continuous VAF. Detecting low-VAF variants requires deep coverage + somatic-specific callers." },
          { type:"single",
            stem:"想偵測「腫瘤中 VAF = 5%」的變異，建議的最低 unique coverage 是？",
            stem_en:"To reliably detect VAF = 5% variants in a tumor, the minimum unique coverage should be?",
            A:"~ 10×", A_en:"~ 10×",
            B:"~ 30×", B_en:"~ 30×",
            C:"~ 60-100×", C_en:"~ 60–100×",
            D:"1000×", D_en:"1000×",
            ans:"C",
            exp:"低 VAF 需要對應的深度才能至少有幾條 alt reads。VAF 5% 通常需 60-100× 才有合理偵測力（&gt; 3-5 條 alt reads）。",
            exp_en:"Low VAFs require enough depth to capture multiple alt reads; VAF 5% typically needs 60–100× for &gt; 3–5 alt reads." },
          { type:"single",
            stem:"Mutect2 跑 paired tumor-normal 模式時，<code>--germline-resource</code> 應使用何種資料？",
            stem_en:"In Mutect2 paired tumor-normal mode, what should <code>--germline-resource</code> contain?",
            A:"COSMIC 體細胞變異", A_en:"COSMIC somatic variants",
            B:"gnomAD allele frequency VCF（含 AF）", B_en:"gnomAD allele frequency VCF (with AF)",
            C:"BAM 檔", C_en:"A BAM file",
            D:"GTF 註釋", D_en:"GTF annotation",
            ans:"B",
            exp:"Mutect2 用 gnomAD AF 估計觀察到的變異作為 germline 的機率，協助區分 germline / somatic。",
            exp_en:"Mutect2 uses gnomAD AF to estimate the probability that a variant is germline, aiding germline / somatic discrimination." }
        ],
        "Variant 3：Filtering": [
          { type:"single",
            stem:"VQSR (Variant Quality Score Recalibration) 至少建議多少樣本才能穩定運作？",
            stem_en:"What sample size does VQSR typically require to work stably?",
            A:"1 個樣本即可", A_en:"1 sample is fine",
            B:"≥ 30 個（人類 WGS / WES）", B_en:"≥ 30 (human WGS / WES)",
            C:"必須 &gt; 10,000 個", C_en:"Must be &gt; 10,000",
            D:"與樣本數無關", D_en:"Independent of sample size",
            ans:"B",
            exp:"VQSR 透過混合高斯模型訓練；&lt; 30 樣本變異點數通常不足以穩定訓練。可改用 hard filter 或 CNNScoreVariants。",
            exp_en:"VQSR fits a Gaussian mixture; with fewer than 30 samples there usually aren't enough variants for stable training. Use hard filters or CNNScoreVariants instead." },
          { type:"single",
            stem:"GATK hard filter 對 SNP 的典型建議門檻為 <code>QD &lt; 2.0</code>。QD 代表？",
            stem_en:"In GATK hard filtering for SNPs, <code>QD &lt; 2.0</code> uses 'QD' meaning?",
            A:"Quality / Depth", A_en:"Quality / Depth",
            B:"Quantile of Depth", B_en:"Quantile of Depth",
            C:"Quality Difference", C_en:"Quality Difference",
            D:"Quality of Discovery", D_en:"Quality of Discovery",
            ans:"A",
            exp:"QD = variant quality / depth (QualByDepth)。低 QD 代表訊號被深度稀釋，常為假陽性。",
            exp_en:"QD = variant quality divided by depth (QualByDepth). Low QD means signal diluted by depth — often a false positive." },
          { type:"multi",
            stem:"以下哪些是常見的 SNP hard filter 指標？（多選）",
            stem_en:"Which are common SNP hard-filter metrics? (Multiple)",
            A:"FS (Fisher strand bias)", A_en:"FS (Fisher strand bias)",
            B:"MQ (mapping quality)", B_en:"MQ (mapping quality)",
            C:"SOR (strand odds ratio)", C_en:"SOR (strand odds ratio)",
            D:"GC content", D_en:"GC content",
            ans:["A","B","C"],
            exp:"FS、MQ、SOR 都是 GATK 標準硬性過濾指標；GC content 並非 GATK 硬過濾欄位。",
            exp_en:"FS, MQ, and SOR are standard GATK hard-filter fields; GC content is not." },
          { type:"tf",
            stem:"是非題：VQSR 是 SNP 與 indel 分開訓練的，不能用同一模型同時處理兩者。",
            stem_en:"True/False: VQSR trains SNP and indel models separately; one model cannot handle both.",
            ans:"T",
            exp:"GATK BP 建議 SNP 與 indel 各跑一次 VariantRecalibrator + ApplyVQSR，因為兩者的 truth set 與訊號特徵不同。",
            exp_en:"GATK BP recommends separate VariantRecalibrator + ApplyVQSR runs for SNPs and indels because truth sets and signal profiles differ." },
          { type:"single",
            stem:"小樣本（n &lt; 30）人類 WGS 在無法跑 VQSR 時，GATK 建議用什麼替代？",
            stem_en:"For small (n &lt; 30) human WGS where VQSR isn't viable, what does GATK suggest as an alternative?",
            A:"刪除所有變異", A_en:"Discard all variants",
            B:"hard filter 或 CNNScoreVariants", B_en:"Hard filter or CNNScoreVariants",
            C:"再做一次 BQSR", C_en:"Re-run BQSR",
            D:"放棄分析", D_en:"Abandon the analysis",
            ans:"B",
            exp:"小樣本時用固定門檻的 hard filter 或 GATK CNNScoreVariants（CNN 分類器，無需大量樣本）。",
            exp_en:"For small cohorts, use fixed-threshold hard filters or GATK CNNScoreVariants (a CNN classifier that doesn't need many samples)." }
        ],
        "Variant 4：Annotation": [
          { type:"single",
            stem:"VEP 中 \"HIGH impact\" 等級的變異典型例子是？",
            stem_en:"What is a typical example of VEP's 'HIGH impact' tier?",
            A:"synonymous variant", A_en:"Synonymous variant",
            B:"stop_gained / frameshift", B_en:"stop_gained / frameshift",
            C:"intron variant", C_en:"Intron variant",
            D:"upstream variant", D_en:"Upstream variant",
            ans:"B",
            exp:"HIGH impact = 嚴重破壞蛋白結構，如 stop gained、frameshift、splice donor/acceptor。",
            exp_en:"HIGH impact = severe protein disruption: stop gained, frameshift, splice donor/acceptor changes." },
          { type:"single",
            stem:"gnomAD 的主要用途是？",
            stem_en:"What is gnomAD primarily used for?",
            A:"提供族群層級的 allele frequency 資料", A_en:"Population allele-frequency data",
            B:"做基因組組裝", B_en:"Genome assembly",
            C:"做 RNA-seq DE", C_en:"RNA-seq DE",
            D:"做 ATAC-seq peak calling", D_en:"ATAC-seq peak calling",
            ans:"A",
            exp:"gnomAD 整合 700k+ exome 與 76k+ genome 個體，提供族群 allele frequency，是區分罕見 / 常見變異的標準。",
            exp_en:"gnomAD aggregates 700k+ exomes and 76k+ genomes for population allele frequency — the standard for rare vs common variant separation." },
          { type:"multi",
            stem:"下列哪些是優先排序臨床顯著變異的合理準則？（多選）",
            stem_en:"Which are reasonable criteria for prioritizing clinically significant variants? (Multiple)",
            A:"gnomAD AF &lt; 1%", A_en:"gnomAD AF &lt; 1%",
            B:"VEP HIGH impact 或 CADD &gt; 20", B_en:"VEP HIGH impact or CADD &gt; 20",
            C:"ClinVar Pathogenic / Likely Pathogenic", C_en:"ClinVar Pathogenic / Likely Pathogenic",
            D:"variant 在 chromosome 22", D_en:"Variant is on chromosome 22",
            ans:["A","B","C"],
            exp:"頻率、影響、臨床標註是優先排序三大主要面向；染色體位置本身不是優先排序依據。",
            exp_en:"Frequency, impact, and clinical annotation are the three main pillars of prioritization; chromosome location alone is not." },
          { type:"single",
            stem:"CADD score &gt; 20 通常代表？",
            stem_en:"What does a CADD score &gt; 20 typically indicate?",
            A:"前 1% 預期最有害的變異", A_en:"Top 1% most deleterious variants",
            B:"完全無害的變異", B_en:"Completely benign",
            C:"無法判讀", C_en:"Uninterpretable",
            D:"低基因組保守度", D_en:"Low genomic conservation",
            ans:"A",
            exp:"CADD PHRED-scaled score：&gt; 20 對應前 1% 預期最有害變異；&gt; 30 對應前 0.1%。",
            exp_en:"CADD PHRED-scaled score: &gt; 20 corresponds to the top 1% most deleterious; &gt; 30 to the top 0.1%." },
          { type:"tf",
            stem:"是非題：ClinVar 對變異的分類包含 Pathogenic、Likely Pathogenic、VUS、Likely Benign、Benign 五級。",
            stem_en:"True/False: ClinVar uses a 5-tier classification: Pathogenic, Likely Pathogenic, VUS, Likely Benign, Benign.",
            ans:"T",
            exp:"這是 ACMG / AMP 標準的五級分類，ClinVar 採用此體系。",
            exp_en:"This is the ACMG / AMP 5-tier scheme used by ClinVar." },
          { type:"single",
            stem:"VEP 中 <code>--pick</code> 選項的作用是？",
            stem_en:"What does VEP's <code>--pick</code> option do?",
            A:"輸出所有轉錄本的註釋", A_en:"Output annotations for all transcripts",
            B:"每個變異只輸出單一最具代表性的轉錄本註釋", B_en:"Output a single most-representative transcript annotation per variant",
            C:"做變異排序", C_en:"Sort variants",
            D:"刪除沒有註釋的變異", D_en:"Drop unannotated variants",
            ans:"B",
            exp:"<code>--pick</code> 依規則挑選一個最具代表性的轉錄本（如 canonical），讓輸出每變異一行，方便下游處理。",
            exp_en:"<code>--pick</code> selects one representative transcript per variant (e.g., canonical) for one-line-per-variant output." }
        ],
        "Variant 5：SV / CNV": [
          { type:"single",
            stem:"以下何者屬於結構變異 (SV)？",
            stem_en:"Which of the following is a structural variant (SV)?",
            A:"單鹼基替換 (SNV)", A_en:"Single-nucleotide variant (SNV)",
            B:"~ 2 kb 的 deletion", B_en:"~ 2 kb deletion",
            C:"synonymous codon change", C_en:"Synonymous codon change",
            D:"single base insertion", D_en:"Single base insertion",
            ans:"B",
            exp:"SV 定義為 &gt; 50 bp 的變異，包含 DEL、DUP、INS、INV、TRA、BND 等。",
            exp_en:"SVs are &gt; 50 bp variants including DEL, DUP, INS, INV, TRA, BND." },
          { type:"multi",
            stem:"以下哪些訊號可用來偵測 SV？（多選）",
            stem_en:"Which signals can be used to detect SVs? (Multiple)",
            A:"read pair 距離異常", A_en:"Abnormal read pair distance",
            B:"split read", B_en:"Split read",
            C:"read depth 異常", C_en:"Abnormal read depth",
            D:"genome assembly", D_en:"Genome assembly",
            ans:["A","B","C","D"],
            exp:"RP、SR、RD 與 de novo assembly 都是 SV 偵測的常用訊號。Manta、Delly、GRIDSS 各取所長。",
            exp_en:"RP, SR, RD, and de novo assembly are all SV detection signals; Manta, Delly, and GRIDSS combine them differently." },
          { type:"single",
            stem:"下列何者最適合 WES 的 CNV 分析？",
            stem_en:"Which is most suitable for WES CNV analysis?",
            A:"Manta SV", A_en:"Manta SV",
            B:"GATK gCNV / CNVkit", B_en:"GATK gCNV / CNVkit",
            C:"DeepVariant", C_en:"DeepVariant",
            D:"Genrich", D_en:"Genrich",
            ans:"B",
            exp:"GATK gCNV、CNVkit 等基於 read depth 的工具適合 WES。Manta 為 WGS SV 工具，WES 因 intron 無覆蓋表現差。",
            exp_en:"Read-depth tools like GATK gCNV and CNVkit suit WES. Manta is a WGS SV tool and performs poorly on WES due to intronic gaps." },
          { type:"tf",
            stem:"是非題：長讀定序（PacBio HiFi / ONT）在偵測 &lt; 1 kb SV 通常比 short read 靈敏度高。",
            stem_en:"True/False: Long-read sequencing (PacBio HiFi / ONT) is typically more sensitive than short reads for SVs &lt; 1 kb.",
            ans:"T",
            exp:"長讀 read 可跨越大部分 SV 與重複序列，能直接觀察 break-point。short read 對 &lt; 1 kb SV 漏報率高。",
            exp_en:"Long reads span most SVs and repeats, observing break-points directly; short reads frequently miss SVs &lt; 1 kb." },
          { type:"single",
            stem:"以下何處最常產生 SV 假陽性，應該過濾？",
            stem_en:"Which regions most often generate SV false positives and should be filtered?",
            A:"基因 promoter 區", A_en:"Gene promoter regions",
            B:"centromere、telomere、segmental duplication", B_en:"Centromeres, telomeres, segmental duplications",
            C:"exon", C_en:"Exon",
            D:"5' UTR", D_en:"5' UTR",
            ans:"B",
            exp:"低複雜度與重複區是 SV 假陽性熱區；建議用 ENCODE blacklist + segmental duplication 過濾。",
            exp_en:"Low-complexity and repetitive regions are SV FP hotspots; filter with ENCODE blacklist + segmental duplication tracks." }
        ]
      },

      "Track 5：Microbiome": {
        "Microbiome 1：16S Amplicon": [
          { type:"single",
            stem:"OTU 與 ASV 最大差別是？",
            stem_en:"What is the key difference between OTU and ASV?",
            A:"OTU 為單鹼基精度；ASV 為 97% 聚類", A_en:"OTU is single-base precision; ASV is 97% clustering",
            B:"ASV 為單鹼基精度（denoising），OTU 為 97% 聚類", B_en:"ASV is single-base precision (denoising); OTU is 97% clustering",
            C:"兩者完全相同", C_en:"They are identical",
            D:"OTU 屬於 shotgun metagenomics", D_en:"OTU is for shotgun metagenomics",
            ans:"B",
            exp:"ASV 用 denoising（如 DADA2）回到「真實」序列，精度到單鹼基；OTU 採 97% similarity 聚類，較粗。",
            exp_en:"ASV uses denoising (e.g., DADA2) to recover 'true' sequences at single-base precision; OTU clusters at 97% similarity (coarser)." },
          { type:"single",
            stem:"Shannon Index 在什麼情境會達最大值？",
            stem_en:"When is the Shannon Index maximized?",
            A:"只有 1 個物種", A_en:"Only 1 species present",
            B:"所有物種比例相同（完美均勻）", B_en:"All species have equal proportions (perfect evenness)",
            C:"前兩個物種占 99%", C_en:"Top 2 species account for 99%",
            D:"無法計算", D_en:"Cannot be computed",
            ans:"B",
            exp:"Shannon H = -Σp·ln(p)。給定物種數 n，當所有 p = 1/n 時 H = ln(n) 為最大。",
            exp_en:"Shannon H = -Σp·ln(p). For n species, H is maximized at p = 1/n with H = ln(n)." },
          { type:"single",
            stem:"以下哪個資料庫常用於 16S rRNA 分類？",
            stem_en:"Which database is commonly used for 16S rRNA classification?",
            A:"SILVA", A_en:"SILVA",
            B:"gnomAD", B_en:"gnomAD",
            C:"ClinVar", C_en:"ClinVar",
            D:"GENCODE", D_en:"GENCODE",
            ans:"A",
            exp:"SILVA 是 16S rRNA 的主流公開資料庫；Greengenes 與 RDP 也常用。",
            exp_en:"SILVA is the leading 16S rRNA database; Greengenes and RDP are also common." },
          { type:"multi",
            stem:"下列哪些是 16S Amplicon 分析的常用工具？（多選）",
            stem_en:"Which are common 16S amplicon analysis tools? (Multiple)",
            A:"DADA2", A_en:"DADA2",
            B:"QIIME2", B_en:"QIIME2",
            C:"phyloseq", C_en:"phyloseq",
            D:"BWA", D_en:"BWA",
            ans:["A","B","C"],
            exp:"前三者是 16S 流程主力（denoising、平台、下游分析）。BWA 是基因組比對工具。",
            exp_en:"The first three are 16S workflow staples (denoising, platform, downstream); BWA is a genome aligner." },
          { type:"tf",
            stem:"是非題：微生物相對豐度為「比例資料」（總和為 1），不適合直接用 t-test 比較。",
            stem_en:"True/False: Microbial relative abundances are compositional data (sum to 1); they should not be compared with t-test directly.",
            ans:"T",
            exp:"compositional 資料違反獨立性假設。應該用 CLR 轉換 + ALDEx2 / ANCOM-BC 等專用工具。",
            exp_en:"Compositional data violate independence assumptions. Use CLR + ALDEx2 / ANCOM-BC etc." },
          { type:"single",
            stem:"Bray-Curtis 距離用於什麼情境？",
            stem_en:"What is Bray-Curtis distance used for?",
            A:"alpha diversity", A_en:"Alpha diversity",
            B:"beta diversity（樣本間差異）", B_en:"Beta diversity (between-sample dissimilarity)",
            C:"序列比對", C_en:"Sequence alignment",
            D:"variant calling", D_en:"Variant calling",
            ans:"B",
            exp:"Bray-Curtis 是經典的 beta diversity 距離度量；UniFrac (含 weighted / unweighted) 也是常用選擇。",
            exp_en:"Bray-Curtis is the classic beta-diversity metric; UniFrac (weighted / unweighted) is also common." },
          { type:"single",
            stem:"DADA2 的「denoising」核心想法是？",
            stem_en:"What is the core idea of DADA2's 'denoising'?",
            A:"刪除所有低品質 read", A_en:"Delete all low-quality reads",
            B:"用機率模型推估「測序錯誤」並校正回真實序列", B_en:"Use a probabilistic model to estimate 'sequencing errors' and correct back to true sequences",
            C:"做 97% similarity 聚類", C_en:"97% similarity clustering",
            D:"做 BLAST 比對", D_en:"Run BLAST",
            ans:"B",
            exp:"DADA2 學習 run-specific 錯誤率，把觀察到的序列拆解為「真實 ASV + 錯誤」，無需 97% clustering。",
            exp_en:"DADA2 learns run-specific error rates and decomposes observed sequences into 'true ASV + errors' — no 97% clustering needed." }
        ],
        "Microbiome 2：Shotgun Metagenomics": [
          { type:"single",
            stem:"以下何者屬於 read-based metagenomics 分類器？",
            stem_en:"Which is a read-based metagenomics classifier?",
            A:"Kraken2", A_en:"Kraken2",
            B:"MEGAHIT", B_en:"MEGAHIT",
            C:"MetaBAT2", C_en:"MetaBAT2",
            D:"CheckM2", D_en:"CheckM2",
            ans:"A",
            exp:"Kraken2 用 k-mer 直接對 reads 分類。MEGAHIT 為 assembler、MetaBAT2 為 binning、CheckM2 為 MAG QC。",
            exp_en:"Kraken2 classifies reads by k-mer. MEGAHIT is an assembler; MetaBAT2 is binning; CheckM2 is MAG QC." },
          { type:"single",
            stem:"關於 MetaPhlAn4，下列敘述何者正確？",
            stem_en:"Which statement about MetaPhlAn4 is correct?",
            A:"基於 whole-genome 對比", A_en:"Based on whole-genome alignment",
            B:"使用 clade-specific marker genes 進行物種分類", B_en:"Uses clade-specific marker genes for species classification",
            C:"做 16S amplicon 分析", C_en:"Does 16S amplicon analysis",
            D:"做 RNA-seq 分析", D_en:"Does RNA-seq analysis",
            ans:"B",
            exp:"MetaPhlAn4 比對 clade-specific marker genes（每物種獨特標記），速度快且記憶體小，是 shotgun 物種分類主流。",
            exp_en:"MetaPhlAn4 maps to clade-specific marker genes (unique per species), being fast and memory-efficient — a mainstream shotgun classifier." },
          { type:"multi",
            stem:"以下哪些是 MAG 重建流程的關鍵步驟？（多選）",
            stem_en:"Which are key steps in MAG reconstruction? (Multiple)",
            A:"組裝 (assembly)", A_en:"Assembly",
            B:"分箱 (binning)", B_en:"Binning",
            C:"品質評估（CheckM2）", C_en:"Quality assessment (CheckM2)",
            D:"做 RNA-seq DE", D_en:"RNA-seq DE",
            ans:["A","B","C"],
            exp:"assembly → binning → MAG QC 是標準三步驟；RNA-seq DE 無關。",
            exp_en:"Assembly → binning → MAG QC is the standard three-step process; RNA-seq DE is unrelated." },
          { type:"single",
            stem:"根據 MIMAG 標準，High Quality MAG 的完整度與汙染門檻是？",
            stem_en:"Per the MIMAG standard, what are the thresholds for a High Quality MAG?",
            A:"&gt; 50% / &lt; 10%", A_en:"&gt; 50% / &lt; 10%",
            B:"&gt; 90% / &lt; 5%", B_en:"&gt; 90% / &lt; 5%",
            C:"&gt; 30% / &lt; 20%", C_en:"&gt; 30% / &lt; 20%",
            D:"&gt; 99% / 0%", D_en:"&gt; 99% / 0%",
            ans:"B",
            exp:"MIMAG（Bowers et al. 2017）：High Quality MAG = 完整度 &gt; 90% 且汙染 &lt; 5%；Medium Quality 是 &gt; 50% / &lt; 10%。",
            exp_en:"MIMAG (Bowers et al. 2017): HQ MAG = completeness &gt; 90% and contamination &lt; 5%; Medium = &gt; 50% / &lt; 10%." },
          { type:"tf",
            stem:"是非題：在人類腸道 shotgun metagenomics 樣本中，預過濾 host (人類) DNA 是必要步驟。",
            stem_en:"True/False: For human gut shotgun metagenomics samples, pre-filtering host (human) DNA is a required step.",
            ans:"T",
            exp:"人類腸道樣本可含 30%+ 人類 DNA。Bowtie2 比對人類基因組過濾後才能準確進行微生物分析。",
            exp_en:"Human gut samples can contain 30%+ human DNA; pre-filter with Bowtie2 against the human genome before microbial analysis." },
          { type:"single",
            stem:"以下哪個工具用於 MAG 的物種分類？",
            stem_en:"Which tool is used for MAG taxonomic classification?",
            A:"GTDB-Tk", A_en:"GTDB-Tk",
            B:"Kraken2", B_en:"Kraken2",
            C:"DADA2", C_en:"DADA2",
            D:"DESeq2", D_en:"DESeq2",
            ans:"A",
            exp:"GTDB-Tk 用 GTDB 資料庫對組裝得到的 MAG 做標準化分類；Kraken2 是 read-level 分類。",
            exp_en:"GTDB-Tk classifies assembled MAGs using the GTDB database; Kraken2 is for read-level classification." }
        ],
        "Microbiome 3：Functional Profiling": [
          { type:"single",
            stem:"HUMAnN3 主要功能是？",
            stem_en:"What does HUMAnN3 primarily do?",
            A:"做 16S amplicon 分析", A_en:"16S amplicon analysis",
            B:"從 shotgun 直接量化 pathway / KO 功能豐度", B_en:"Quantify pathway / KO functional abundance from shotgun directly",
            C:"做 MAG 組裝", C_en:"MAG assembly",
            D:"做 phylogenetic tree", D_en:"Build phylogenetic trees",
            ans:"B",
            exp:"HUMAnN3 把 shotgun reads 比對到 UniRef / MetaCyc，產生 pathway abundance 與 KO 等功能輪廓。",
            exp_en:"HUMAnN3 maps shotgun reads to UniRef / MetaCyc, producing pathway abundance and KO functional profiles." },
          { type:"single",
            stem:"PICRUSt2 與 HUMAnN3 在使用情境上的最大差別是？",
            stem_en:"What's the key difference in use case between PICRUSt2 and HUMAnN3?",
            A:"PICRUSt2 從 shotgun 直接量化；HUMAnN3 從 16S 推估", A_en:"PICRUSt2 quantifies from shotgun; HUMAnN3 predicts from 16S",
            B:"PICRUSt2 從 16S 推估功能；HUMAnN3 從 shotgun 直接量化", B_en:"PICRUSt2 predicts function from 16S; HUMAnN3 quantifies from shotgun",
            C:"兩者完全相同", C_en:"They are identical",
            D:"PICRUSt2 做 OTU 聚類", D_en:"PICRUSt2 does OTU clustering",
            ans:"B",
            exp:"PICRUSt2 從 16S ASV 推估「可能的功能」（不確定性高）；HUMAnN3 從 shotgun reads 量化「實際偵測到的基因」（精準）。",
            exp_en:"PICRUSt2 predicts likely function from 16S ASVs (uncertain); HUMAnN3 quantifies actually detected genes from shotgun reads (accurate)." },
          { type:"tf",
            stem:"是非題：把 16S PICRUSt2 推估結果當作實驗事實，不需 shotgun 驗證。",
            stem_en:"True/False: PICRUSt2 16S-based predictions can be treated as experimental ground truth without shotgun validation.",
            ans:"F",
            exp:"PICRUSt2 為「推估」，準確度依賴參考樹涵蓋度，且對 unique 環境變數錯誤偏大。談機制前要 shotgun 驗證。",
            exp_en:"PICRUSt2 only predicts; accuracy depends on tree coverage and degrades for novel environments. Validate with shotgun before mechanistic claims." },
          { type:"multi",
            stem:"下列哪些是適合微生物 compositional 資料的差異豐度分析工具？（多選）",
            stem_en:"Which are suitable differential abundance tools for compositional microbiome data? (Multiple)",
            A:"ALDEx2", A_en:"ALDEx2",
            B:"ANCOM-BC", B_en:"ANCOM-BC",
            C:"MaAsLin2", C_en:"MaAsLin2",
            D:"vanilla Pearson t-test", D_en:"Vanilla Pearson t-test",
            ans:["A","B","C"],
            exp:"前三者皆考慮 compositional 性質；naive t-test 對 compositional 資料容易誤判。",
            exp_en:"The first three handle compositionality; a naive t-test on compositional data often misleads." },
          { type:"single",
            stem:"PICRUSt2 的 NSTI（Nearest Sequenced Taxon Index）數值越高，代表？",
            stem_en:"In PICRUSt2, what does a higher NSTI (Nearest Sequenced Taxon Index) indicate?",
            A:"預測越可信", A_en:"Higher prediction confidence",
            B:"ASV 離已知參考基因組越遠，預測越不可信", B_en:"The ASV is farther from known reference genomes — less reliable prediction",
            C:"與可信度無關", C_en:"Unrelated to reliability",
            D:"代表豐度極高", D_en:"Indicates very high abundance",
            ans:"B",
            exp:"NSTI 是 ASV 到參考基因組的「距離」；越遠代表參考越少，推估越不確定，常見過濾門檻 NSTI &lt; 2。",
            exp_en:"NSTI is the 'distance' from an ASV to reference genomes; larger = less reference support, less reliable. Common filter: NSTI &lt; 2." }
        ]
      }
    }
  }
};
